"""Ground truth: 126 case studies for backtesting the Jyotish interpretation engine.

Sources:
  - KN Rao (60): Predictive Techniques, Jaimini Chara Dasha, Karakamsha & Mandook Dasha, Dasha Nirnay
  - BV Raman (34): Hindu Predictive Astrology
  - Sanjay Rath (32): Crux of Vedic Astrology, Vimsottari & Udu Dasas

Rules followed:
  - Only planets/positions EXPLICITLY stated in case text are included
  - Lagna set to None if not mentioned
  - House numbers are from lagna unless noted
  - partial=True if case lacks chart specifics for full reconstruction
"""

GROUND_TRUTH = [
    # ==========================================================================
    # KN RAO BOOK 1: Predictive Techniques (CS-001..008)
    # ==========================================================================
    {'id':'KNR-CS-001','name':'Dr. Nagendra Singh','lagna':None,
     'planets':{'Mars':{'rashi':'Leo','role':'10th lord'},'Jupiter':{'rashi':'Taurus'},'Venus':{'house_in_d10':10},'Ketu':{'house':3,'house_in_d10':10}},
     'dasha':{'md':'Rahu','ad':'Venus','pd':'Ketu'},'outcome_domain':'career','outcome_positive':True,
     'outcome_description':'Won election to International Court of Justice after difficult contest',
     'key_pattern':'dashamsha_override_for_career','key_lesson':'D-10 clinches career; resolves birth-chart vs navamsha contradictions',
     'reasoning_chain':['10th lord Mars Leo+Jupiter association','D-10 Venus/Ketu 10th=triumph','Birth chart showed fight but D-10 victory'],
     'source':'KN Rao - Predictive Techniques','partial':False},
    {'id':'KNR-CS-002','name':'Indira Gandhi PM Pattern','lagna':None,
     'planets':{'Mars':{'role':'10th lord'}},'dasha':None,
     'outcome_domain':'political','outcome_positive':True,
     'outcome_description':'10th lord Mars+Jupiter association repeated at each political elevation',
     'key_pattern':'10th_lord_jupiter_association','key_lesson':'Same transit yoga across charts=reliable template',
     'reasoning_chain':['10th lord Mars+Jupiter when PM','Same pattern Jan 1980'],
     'source':'KN Rao - Predictive Techniques','partial':True},
    {'id':'KNR-CS-003','name':'K.C. Saxena','lagna':None,
     'planets':{'Mercury':{'house':4},'Moon':{'role':'4th lord'},'Jupiter':{'role':'9th lord'},'Sun':{'role':'5th lord'},'Saturn':{'house':7,'dignity':'exalted'}},
     'dasha':None,'outcome_domain':'death','outcome_positive':False,
     'outcome_description':'Brilliant astrologer died Saturn period; 7th house maraka even exalted',
     'key_pattern':'saturn_7th_maraka_exalted','key_lesson':'Planet gives achievement AND death; Mercury 4th=astrology talent',
     'reasoning_chain':['Mercury 4th aspecting 10th','Gajakesari Moon 4th+Jupiter 9th','Saturn exalted 7th=maraka died Saturn period'],
     'source':'KN Rao - Predictive Techniques','partial':False},
    {'id':'KNR-CS-004','name':'Saxena Patient','lagna':None,
     'planets':{'Rahu':{'house':5}},'dasha':None,
     'outcome_domain':'health','outcome_positive':False,
     'outcome_description':'Chronic ailment; Gnathikaraka+Rahu 5th; Yogini dasha unhelpful',
     'key_pattern':'atmakaraka_dasha_health','key_lesson':'Not all dashas work equally; Jaimini karaka-based better for health',
     'reasoning_chain':['AK dasha scrutiny','Kumbha+GK+Rahu 5th=danger','Yogini unhelpful'],
     'source':'KN Rao - Predictive Techniques','partial':True},
    {'id':'KNR-CS-005','name':'Saturn-Venus Period Multiple','lagna':None,
     'planets':{},'dasha':None,'outcome_domain':'career','outcome_positive':None,
     'outcome_description':'Saturn-Venus periods: discipline vs pleasure tension across many charts',
     'key_pattern':'saturn_venus_tension','key_lesson':'Study period combos across charts for themes',
     'reasoning_chain':['Multiple cases','Saturn=delays Venus=relationships','House rulerships modify'],
     'source':'KN Rao - Predictive Techniques','partial':True},
    {'id':'KNR-CS-006','name':'Chaitanya Mahaprabhu','lagna':None,
     'planets':{},'dasha':None,'outcome_domain':'spiritual','outcome_positive':True,
     'outcome_description':'World-changing saint; classical spiritual yogas',
     'key_pattern':'spiritual_yogas_5_9_12','key_lesson':'Read charts at appropriate level; spiritual not reducible to mundane',
     'reasoning_chain':['5th 9th 12th examined','Jupiter wisdom karaka','AK spiritual houses'],
     'source':'KN Rao - Predictive Techniques','partial':True},
    {'id':'KNR-CS-007','name':'Prabhupada ISKCON','lagna':None,
     'planets':{},'dasha':None,'outcome_domain':'spiritual','outcome_positive':True,
     'outcome_description':'Founded ISKCON age 69; global mission late activation',
     'key_pattern':'late_life_activation','key_lesson':'Greatest contribution late; dasha determines timing',
     'reasoning_chain':['9th 10th 7th examined','Rajayoga+spiritual','Late dasha activation'],
     'source':'KN Rao - Predictive Techniques','partial':True},
    {'id':'KNR-CS-008','name':'USA Cultural Analysis','lagna':None,
     'planets':{},'dasha':None,'outcome_domain':'political','outcome_positive':None,
     'outcome_description':'Mundane cultural context; not chart analysis',
     'key_pattern':'mundane_cultural_context','key_lesson':'Mundane astrology needs cultural framework',
     'reasoning_chain':['Cultural context'],'source':'KN Rao - Predictive Techniques','partial':True},

    # KN RAO BOOK 2: Jaimini Chara Dasha (CS-009..018)
    {'id':'KNR-CS-009','name':'Chart1 Education/Career/Marriage','lagna':None,
     'planets':{'Mercury':{'retrograde':True}},'dasha':None,
     'outcome_domain':'career','outcome_positive':True,
     'outcome_description':'All-India exams; married last Scorpio sub (DK present)',
     'key_pattern':'chara_dasha_dk_marriage','key_lesson':'Chara Dasha: houses FROM dasha sign; DK times marriage',
     'reasoning_chain':['Virgo 12yr Libra 1yr Scorpio 10yr','Scorpio 5th=education','Sag sub 10th=govt','Last sub DK=marriage'],
     'source':'KN Rao - Jaimini Chara Dasha','partial':True},
    {'id':'KNR-CS-010','name':'Father Son Business','lagna':None,
     'planets':{},'dasha':None,'outcome_domain':'wealth','outcome_positive':True,
     'outcome_description':'Father self-made(Saturn on AmK); son inherited(Jupiter on AmK)',
     'key_pattern':'amk_saturn_vs_jupiter','key_lesson':'AmK reveals career nature; Saturn=self-made Jupiter=inherited',
     'reasoning_chain':['Father AmK=Moon+Saturn 11th','Son AmK=Mercury+Jupiter 11th'],
     'source':'KN Rao - Jaimini Chara Dasha','partial':True},
    {'id':'KNR-CS-011','name':'Businessman Ruined','lagna':None,
     'planets':{'Sun':{'dignity':'debilitated','role':'AmK'},'Mercury':{'retrograde':True}},
     'dasha':None,'outcome_domain':'wealth','outcome_positive':False,
     'outcome_description':'Business ruined 1975 retrograde Mercury dasha; debilitated AmK',
     'key_pattern':'debilitated_amk_ruin','key_lesson':'Debilitated karakas: initial success then failure; retrograde=hidden problems',
     'reasoning_chain':['AmK=debilitated Sun','Enemy aspect','Retro Mercury dasha=ruin'],
     'source':'KN Rao - Jaimini Chara Dasha','partial':True},
    {'id':'KNR-CS-012','name':'Marriage Chara 1','lagna':None,'planets':{},'dasha':None,
     'outcome_domain':'marriage','outcome_positive':True,
     'outcome_description':'Marriage timed by Chara Dasha activating DK sign',
     'key_pattern':'dk_upapada_chara','key_lesson':'Jaimini marriage: DK+Upapada+Chara Dasha',
     'reasoning_chain':['DK position','7th from Upapada','Chara activating DK','Navamsha confirm'],
     'source':'KN Rao - Jaimini Chara Dasha','partial':True},
    {'id':'KNR-CS-013','name':'Marriage Chara 2','lagna':None,'planets':{},'dasha':None,
     'outcome_domain':'marriage','outcome_positive':True,
     'outcome_description':'Marriage: DK+Upapada+Pada+Navamsha converge',
     'key_pattern':'jaimini_convergence','key_lesson':'Never single indicator; convergence needed',
     'reasoning_chain':['Same method different chart','Pada cross-verified','Navamsha confirm'],
     'source':'KN Rao - Jaimini Chara Dasha','partial':True},
    {'id':'KNR-CS-014','name':'Marriage Chara 3 Karakamsha','lagna':None,'planets':{},'dasha':None,
     'outcome_domain':'marriage','outcome_positive':True,
     'outcome_description':'Marriage: Chara activates both DK and Karakamsha',
     'key_pattern':'karakamsha_dk_marriage','key_lesson':'Soul-level(Karakamsha)+spouse(DK) both must activate',
     'reasoning_chain':['Chara primary','Karakamsha verify','Sign relates both DK+Karakamsha'],
     'source':'KN Rao - Jaimini Chara Dasha','partial':True},
    {'id':'KNR-CS-015','name':'Indira Gandhi Marriage Pada','lagna':None,'planets':{},'dasha':None,
     'outcome_domain':'marriage','outcome_positive':False,
     'outcome_description':'Padas kendras yet disastrous marriage; rule disproven',
     'key_pattern':'pada_rule_disproven','key_lesson':'Never single Jaimini principle; cross-verify always',
     'reasoning_chain':['Pada lagna+7th kendras','Marriage terrible','Rule incomplete'],
     'source':'KN Rao - Jaimini Chara Dasha','partial':True},
    {'id':'KNR-CS-016','name':'Brahma Calculation','lagna':None,'planets':{},'dasha':None,
     'outcome_domain':'death','outcome_positive':None,
     'outcome_description':'Neelakantha Brahma method validated on dead persons',
     'key_pattern':'brahma_sthira_dasha','key_lesson':'When classical fails seek commentary; test on known deaths',
     'reasoning_chain':['Standard fails','Neelakantha 6/8/12 lords excl Saturn','Tested=accurate'],
     'source':'KN Rao - Jaimini Chara Dasha','partial':True},
    {'id':'KNR-CS-017','name':'Chara Dasha Discovery','lagna':None,'planets':{},'dasha':None,
     'outcome_domain':'education','outcome_positive':True,
     'outcome_description':'Working Chara Dasha discovered; Chitrapaksha only',
     'key_pattern':'chara_dasha_research','key_lesson':'Must work on actual charts; birth time paramount; Chitrapaksha',
     'reasoning_chain':['Commentaries confusing','Train journey discovery','Tested 16 dashas'],
     'source':'KN Rao - Jaimini Chara Dasha','partial':True},
    {'id':'KNR-CS-018','name':'Seven vs Eight Karakas','lagna':None,'planets':{},'dasha':None,
     'outcome_domain':'education','outcome_positive':None,
     'outcome_description':'7 karakas(excl Rahu) better than 8',
     'key_pattern':'seven_karakas','key_lesson':'Test both; research overturns assumption',
     'reasoning_chain':['Tested many horoscopes','7 better'],'source':'KN Rao - Jaimini Chara Dasha','partial':True},

    # KN RAO BOOK 3: Karakamsha & Mandook Dasha (CS-019..026)
    {'id':'KNR-CS-019','name':'Four Engineers Karakamsha','lagna':None,'planets':{},'dasha':None,
     'outcome_domain':'education','outcome_positive':True,
     'outcome_description':'Karakamsha patterns for engineering: Mars/Saturn/Rahu',
     'key_pattern':'karakamsha_technical','key_lesson':'Karakamsha=education nature; Mars/Saturn/Rahu=technical',
     'reasoning_chain':['AK Navamsha=Karakamsha','Mars/Saturn/Rahu=engineering'],
     'source':'KN Rao - Karakamsha & Mandook Dasha','partial':True},
    {'id':'KNR-CS-020','name':'Six Artists Karakamsha','lagna':None,'planets':{},'dasha':None,
     'outcome_domain':'career','outcome_positive':True,
     'outcome_description':'Karakamsha arts: Venus/Moon connections',
     'key_pattern':'karakamsha_artistic','key_lesson':'Venus/Moon=arts; same method different planets=different career',
     'reasoning_chain':['Venus Moon 2nd in Karakamsha','Career dasha verified'],
     'source':'KN Rao - Karakamsha & Mandook Dasha','partial':True},
    {'id':'KNR-CS-021','name':'Three Famous Meena Karakamsha','lagna':None,'planets':{},'dasha':None,
     'outcome_domain':'spiritual','outcome_positive':None,
     'outcome_description':'Pisces Karakamsha NOT=salvation; criminals have it',
     'key_pattern':'meena_karakamsha_myth','key_lesson':'Never take sutra literally without testing',
     'reasoning_chain':['Sutra: Meena=salvation','Three famous=worldly not spiritual','Criminals too'],
     'source':'KN Rao - Karakamsha & Mandook Dasha','partial':True},
    {'id':'KNR-CS-022','name':'Indira Pada Marriage','lagna':None,'planets':{},'dasha':None,
     'outcome_domain':'marriage','outcome_positive':False,
     'outcome_description':'Padas kendras yet disastrous marriage',
     'key_pattern':'pada_kendra_disproven','key_lesson':'Famous charts test rules; look for additional conditions',
     'reasoning_chain':['Pada kendra','Terrible marriage','Rule incomplete'],
     'source':'KN Rao - Karakamsha & Mandook Dasha','partial':True},
    {'id':'KNR-CS-023','name':'Young Man 1962 Mandook','lagna':None,'planets':{},'dasha':None,
     'outcome_domain':'career','outcome_positive':None,
     'outcome_description':'Mandook applied: 4+ planets kendras',
     'key_pattern':'mandook_4_kendra','key_lesson':'Not every dasha applies; check applicability',
     'reasoning_chain':['4+ planets kendras=applicable','Verified events'],
     'source':'KN Rao - Karakamsha & Mandook Dasha','partial':True},
    {'id':'KNR-CS-024','name':'KN Rao Own Mandook','lagna':None,'planets':{},'dasha':None,
     'outcome_domain':'career','outcome_positive':True,
     'outcome_description':'Mandook timed siblings initiation authorship foreign travel',
     'key_pattern':'mandook_multiple','key_lesson':'Test on own chart; variety of events',
     'reasoning_chain':['Siblings 3rd','Initiation 9/12','Authorship 5th','Foreign 9/12'],
     'source':'KN Rao - Karakamsha & Mandook Dasha','partial':True},
    {'id':'KNR-CS-025','name':'Two Ex-PMs Rise Fall','lagna':None,'planets':{},'dasha':None,
     'outcome_domain':'political','outcome_positive':None,
     'outcome_description':'Rise and fall via Mandook Dasha',
     'key_pattern':'rajayoga_shelf_life','key_lesson':'Rajayogas have shelf life; every rise has fall',
     'reasoning_chain':['Rajayogas','Rise dasha','Fall dasha'],
     'source':'KN Rao - Karakamsha & Mandook Dasha','partial':True},
    {'id':'KNR-CS-026','name':'Quick Reading 12 Rashi','lagna':None,'planets':{},'dasha':None,
     'outcome_domain':'education','outcome_positive':None,
     'outcome_description':'Systematic scan; 100+ charts practice needed',
     'key_pattern':'quick_reading','key_lesson':'Speed from practice; 100+ charts; pattern recognition not psychic',
     'reasoning_chain':['Each rashi reference','Assess planets','Practice 100+'],
     'source':'KN Rao - Karakamsha & Mandook Dasha','partial':True},

    # KN RAO BOOK 4: Dasha Nirnay (CS-027..060)
    {'id':'KNR-CS-027','name':'Ex1 Mental Abnormality','lagna':None,'planets':{},'dasha':None,
     'outcome_domain':'health','outcome_positive':False,
     'outcome_description':'Mental breakdown: afflicted Moon/Mercury/4th/5th activated',
     'key_pattern':'moon_mercury_4_5_mental','key_lesson':'Mental health: Moon Mercury 4th 5th from all three lagnas',
     'reasoning_chain':['Moon afflictions','4th emotional 5th intellect','Mercury nervous','Dasha trigger'],
     'source':'KN Rao - Dasha Nirnay','partial':True},
    {'id':'KNR-CS-028','name':'Ex10 Father Hanged','lagna':None,
     'planets':{'Sun':{'role':'9th lord','dignity':'inimical'},'Mars':{},'Jupiter':{'role':'8th from 9th'},'Mercury':{'role':'2nd from 9th'}},
     'dasha':{'md':'Jupiter','ad':'Mercury'},'outcome_domain':'death','outcome_positive':False,
     'outcome_description':'Father hanged Jupiter/Mercury; markesh from 9th',
     'key_pattern':'derived_chart_violent','key_lesson':'Derived chart; Mars/Saturn=violent death',
     'reasoning_chain':['9th papakartari','9th lord Sun inimical+Mars','Jup/Merc markesh from 9th','Hanging'],
     'source':'KN Rao - Dasha Nirnay','partial':False},
    {'id':'KNR-CS-029','name':'Indira Rise Fall','lagna':'Cancer',
     'planets':{'Moon':{'dignity':'debilitated'},'Mars':{'role':'10th lord'},'Saturn':{'role':'7th lord'}},
     'dasha':{'md':'Saturn','ad':'Rahu'},'outcome_domain':'political','outcome_positive':None,
     'outcome_description':'PM ~20yrs; assassinated 31-10-1984 Saturn/Rahu',
     'key_pattern':'rajayoga_maraka_coexist','key_lesson':'7th lord always maraka; rajayoga+maraka coexist',
     'reasoning_chain':['Gajakesari','Saturn 7th=maraka','Rahu sub','Malefic transit all lagnas'],
     'source':'KN Rao - Dasha Nirnay','partial':False},
    {'id':'KNR-CS-030','name':'Sub-Period 6/8/12','lagna':None,'planets':{},'dasha':None,
     'outcome_domain':'career','outcome_positive':False,
     'outcome_description':'AD in 6/8/12 from MD destroys honour',
     'key_pattern':'ad_6_8_12','key_lesson':'Check position AND friendship between dasha lords',
     'reasoning_chain':['6/8/12=destroys honour','Enemy=maximum damage'],
     'source':'KN Rao - Dasha Nirnay','partial':True},
    {'id':'KNR-CS-031','name':'Ex38 Marriage','lagna':None,
     'planets':{'Moon':{'house':4,'role':'7th lord'}},'dasha':{'md':'Moon','ad':'Moon'},
     'outcome_domain':'marriage','outcome_positive':True,
     'outcome_description':'Married Mar 1983 Moon/Moon; Poornima=Moon benefic',
     'key_pattern':'poornima_moon_marriage','key_lesson':'Lunar phase changes Moon nature',
     'reasoning_chain':['Moon 7th lord 4th strong','Poornima=benefic','Karaka favorable'],
     'source':'KN Rao - Dasha Nirnay','partial':False},
    {'id':'KNR-CS-032','name':'Ex39 Business Loss','lagna':None,
     'planets':{'Jupiter':{'house':2,'dignity':'friendly'}},'dasha':None,
     'outcome_domain':'wealth','outcome_positive':False,
     'outcome_description':'Prospered Venus; declined next dasha',
     'key_pattern':'dasha_transition_loss','key_lesson':'Good dasha masks weakness; check next dasha',
     'reasoning_chain':['Venus/Jupiter lucky','Venus prosperous','Next=losses'],
     'source':'KN Rao - Dasha Nirnay','partial':True},
    {'id':'KNR-CS-033','name':'Ex70 Judge','lagna':None,
     'planets':{'Jupiter':{'dignity':'own sign'},'Saturn':{'house':2,'dignity':'friendly'},'Venus':{'role':'10th lord'}},
     'dasha':{'md':'Jupiter','ad':'Saturn'},'outcome_domain':'career','outcome_positive':True,
     'outcome_description':'Judge 1977 Jup/Sat; Sessions Judge 1996 Sat/Ven',
     'key_pattern':'triple_lagna_10th','key_lesson':'Event when house activated from all three lagnas',
     'reasoning_chain':['Jupiter own sign','10th aspected Ven/Merc','Jupiter 10th all lagnas','Promotion Sat/Ven'],
     'source':'KN Rao - Dasha Nirnay','partial':False},
    {'id':'KNR-CS-034','name':'Ex71 Wife Burns','lagna':None,'planets':{},
     'dasha':{'md':'Venus','ad':'Rahu'},'outcome_domain':'death','outcome_positive':False,
     'outcome_description':'Wife burns 01-10-1989; fiery 7th all lagnas',
     'key_pattern':'fiery_7th_triple','key_lesson':'Planet results modified by aspects; triple lagna shows danger type',
     'reasoning_chain':['7th asc: Sat+Mars+Rahu','7th Moon: Rahu+Mars','7th Sun: Leo fiery','Mars aspects Rahu'],
     'source':'KN Rao - Dasha Nirnay','partial':False},
    {'id':'KNR-CS-035','name':'Indira Complete Life','lagna':'Cancer',
     'planets':{'Moon':{'role':'lagna lord'},'Jupiter':{'retrograde':True},'Mars':{'dignity':'exalted'}},
     'dasha':None,'outcome_domain':'political','outcome_positive':None,
     'outcome_description':'Marriage 1942; sons 1944/46; PM 1966; death 1984',
     'key_pattern':'jupiter_saturn_triple','key_lesson':'Jupiter=positive Saturn=death; both from all three lagnas',
     'reasoning_chain':['Marriage: Jup 7th all','Sons: Jup 5th all','PM: Jup all','Death: Sat all'],
     'source':'KN Rao - Dasha Nirnay','partial':False},
    {'id':'KNR-CS-036','name':'Ex73 Late Marriage Female Child','lagna':None,
     'planets':{'Jupiter':{'house':7,'retrograde':True},'Mars':{'rashi':'Sagittarius','role':'7th lord'},'Saturn':{'role':'4/5 lord','house':12}},
     'dasha':{'md':'Saturn','ad':'Moon'},'outcome_domain':'marriage','outcome_positive':True,
     'outcome_description':'Marriage 32 (1984); female child 1987; delay=dasha not chart',
     'key_pattern':'good_7th_late_dasha','key_lesson':'Good house not early; dasha must favor; Saturn=female',
     'reasoning_chain':['Good 7th late dasha','Sat/Moon marriage','Female: Saturn female sign transit'],
     'source':'KN Rao - Dasha Nirnay','partial':False},
    {'id':'KNR-CS-037','name':'Ex74 Infant Death 4d','lagna':None,
     'planets':{'Mars':{'house':8,'role':'lagna+6th'},'Venus':{'house':8,'role':'7th lord'},'Jupiter':{'house':2,'role':'2nd lord'}},
     'dasha':{'md':'Moon','ad':'Rahu'},'outcome_domain':'death','outcome_positive':False,
     'outcome_description':'Died day 4; weak lagna+markesh dominance',
     'key_pattern':'infant_markesh','key_lesson':'Infant: lagna+markesh+dasha+4th house+Saturn transit',
     'reasoning_chain':['Retro Saturn aspects asc','Mars+Venus 8th inimical','Jup/Ven markesh','Saturn all lagnas'],
     'source':'KN Rao - Dasha Nirnay','partial':False},
    {'id':'KNR-CS-038','name':'Ex75 IAS Officer','lagna':'Leo',
     'planets':{'Sun':{'role':'lagna lord'}},'dasha':{'md':'Moon','ad':'Mercury'},
     'outcome_domain':'career','outcome_positive':True,
     'outcome_description':'IAS 11-05-1959; Jupiter 10th all lagnas',
     'key_pattern':'royal_govt','key_lesson':'Govt: Sun+Jupiter; Jupiter aspect house+dasha lords',
     'reasoning_chain':['Leo Sun=royal','Jupiter(R) Sun 10th','Jupiter all lagnas+both dasha lords'],
     'source':'KN Rao - Dasha Nirnay','partial':False},
    {'id':'KNR-CS-039','name':'Ex2-3 Parent Death','lagna':None,'planets':{},'dasha':None,
     'outcome_domain':'death','outcome_positive':False,'outcome_description':'Parent death derived markesh',
     'key_pattern':'derived_parent','key_lesson':'Chart within chart for relatives',
     'reasoning_chain':['9th/4th derived lagna','Markesh from derived'],'source':'KN Rao - Dasha Nirnay','partial':True},
    {'id':'KNR-CS-040','name':'Ex4 Foreign Travel','lagna':None,'planets':{},'dasha':None,
     'outcome_domain':'career','outcome_positive':True,'outcome_description':'Foreign: 9th/12th/Rahu',
     'key_pattern':'9_12_rahu_foreign','key_lesson':'9th+12th+Rahu=foreign indicators',
     'reasoning_chain':['9th journeys','12th foreign','Rahu connections'],'source':'KN Rao - Dasha Nirnay','partial':True},
    {'id':'KNR-CS-041','name':'Ex5-6 Two Divorces','lagna':None,'planets':{},'dasha':None,
     'outcome_domain':'marriage','outcome_positive':False,'outcome_description':'Divorce: 6th-7th connection',
     'key_pattern':'6_7_divorce','key_lesson':'Divorce needs 6th with 7th',
     'reasoning_chain':['7th affliction','6th-7th connection','Dasha activating'],'source':'KN Rao - Dasha Nirnay','partial':True},
    {'id':'KNR-CS-042','name':'Ex7 Suicide Attempt','lagna':None,'planets':{},'dasha':None,
     'outcome_domain':'health','outcome_positive':False,'outcome_description':'Suicide: Moon/4th/lagna multi-affliction',
     'key_pattern':'suicide_layers','key_lesson':'Suicide needs multiple mental layers activated simultaneously',
     'reasoning_chain':['Lagna affliction','Moon+4th','8th activation','Mars-Saturn self'],'source':'KN Rao - Dasha Nirnay','partial':True},
    {'id':'KNR-CS-043','name':'Ex8-9 Death+Accident','lagna':None,'planets':{},'dasha':None,
     'outcome_domain':'death','outcome_positive':False,'outcome_description':'Death markesh; accident Mars/6/8',
     'key_pattern':'mars_6_8_accident','key_lesson':'Accidents=Mars+6th/8th; death=markesh',
     'reasoning_chain':['Markesh dasha','Mars+6+8','Transit verify'],'source':'KN Rao - Dasha Nirnay','partial':True},
    {'id':'KNR-CS-044','name':'Ex12 Child Birth','lagna':None,'planets':{},'dasha':None,
     'outcome_domain':'children','outcome_positive':True,'outcome_description':'Child: 5th+Jupiter transit',
     'key_pattern':'5th_jupiter_child','key_lesson':'Jupiter 5th from all three=childbirth trigger',
     'reasoning_chain':['5th house/lord/karaka','Dasha 5th connected','Jupiter 5th all three'],'source':'KN Rao - Dasha Nirnay','partial':True},
    {'id':'KNR-CS-045','name':'Ex13-14 Operation+Husband','lagna':None,'planets':{},'dasha':None,
     'outcome_domain':'health','outcome_positive':False,'outcome_description':'Surgery Mars+8th; husband 8th=2nd from 7th',
     'key_pattern':'mars_surgery','key_lesson':'Spouse death: 8th=2nd from 7th=markesh',
     'reasoning_chain':['Mars+8+6=operation','2nd from 7th=spouse markesh'],'source':'KN Rao - Dasha Nirnay','partial':True},
    {'id':'KNR-CS-046','name':'Ex15-17 Husband Death x3','lagna':None,'planets':{},'dasha':None,
     'outcome_domain':'death','outcome_positive':False,'outcome_description':'Husband death 7/8 consistent',
     'key_pattern':'7_8_husband','key_lesson':'8th=markesh husband AND widowhood wife',
     'reasoning_chain':['7+8 houses','Mars/Saturn 7th','Jupiter affliction','Saturn 7th all'],'source':'KN Rao - Dasha Nirnay','partial':True},
    {'id':'KNR-CS-047','name':'Ex18 Stillbirth','lagna':None,'planets':{},'dasha':None,
     'outcome_domain':'children','outcome_positive':False,'outcome_description':'Stillbirth: 5th+derived markesh(6/11)',
     'key_pattern':'stillbirth_5_6_11','key_lesson':'Same dasha birth AND death if 5th+6th/11th active',
     'reasoning_chain':['5th affliction','Jupiter weak','Markesh 6th+11th'],'source':'KN Rao - Dasha Nirnay','partial':True},
    {'id':'KNR-CS-048','name':'Ex19 Death','lagna':None,'planets':{},'dasha':None,
     'outcome_domain':'death','outcome_positive':False,'outcome_description':'Death markesh+Saturn triple transit',
     'key_pattern':'markesh_saturn','key_lesson':'Longevity: markesh+badhaka+triple Saturn',
     'reasoning_chain':['Markesh 2/7','Badhaka','Saturn all three'],'source':'KN Rao - Dasha Nirnay','partial':True},
    {'id':'KNR-CS-049','name':'Ex20-21 Political Rise/Fall','lagna':None,'planets':{},'dasha':None,
     'outcome_domain':'political','outcome_positive':None,'outcome_description':'Rise rajayoga; fall dusthana dasha',
     'key_pattern':'rajayoga_dusthana','key_lesson':'Check both rise AND fall',
     'reasoning_chain':['Rajayoga=rise','6/8/12=fall','Jupiter rise Saturn fall'],'source':'KN Rao - Dasha Nirnay','partial':True},
    {'id':'KNR-CS-050','name':'Ex22 Rajayoga','lagna':None,'planets':{},'dasha':None,
     'outcome_domain':'career','outcome_positive':True,'outcome_description':'Rajayoga only in yoga planet dasha+transit',
     'key_pattern':'rajayoga_activation','key_lesson':'Rajayoga=promise; needs dasha+transit',
     'reasoning_chain':['Yoga planets','Strength','Dasha productive years','Jupiter transit'],'source':'KN Rao - Dasha Nirnay','partial':True},
    {'id':'KNR-CS-051','name':'Ex47-48 Political Rise x2','lagna':None,'planets':{},'dasha':None,
     'outcome_domain':'political','outcome_positive':True,'outcome_description':'Political: rajayoga+Jupiter 10th all',
     'key_pattern':'sun_jupiter_political','key_lesson':'Sun+Jupiter key for political',
     'reasoning_chain':['9/10 rajayogas','Sun royal','10th lord dasha','Jupiter 10th all'],'source':'KN Rao - Dasha Nirnay','partial':True},
    {'id':'KNR-CS-052','name':'Ex53-54 Burns x2','lagna':None,'planets':{},'dasha':None,
     'outcome_domain':'death','outcome_positive':False,'outcome_description':'Fire death: fiery on maraka',
     'key_pattern':'fiery_maraka','key_lesson':'8th element shows death manner',
     'reasoning_chain':['Mars Sun fire signs maraka','8th fire','Fire markesh dasha'],'source':'KN Rao - Dasha Nirnay','partial':True},
    {'id':'KNR-CS-053','name':'Ex55-56 Rise+Scandal','lagna':None,'planets':{},'dasha':None,
     'outcome_domain':'political','outcome_positive':None,'outcome_description':'Same chart rise AND scandal different dashas',
     'key_pattern':'rise_scandal','key_lesson':'Same planet gives rise and scandal via dual lordships',
     'reasoning_chain':['Rise: rajayoga+10th','Scandal: 6+8','Different dashas'],'source':'KN Rao - Dasha Nirnay','partial':True},
    {'id':'KNR-CS-054','name':'Ex59 Conspiracy','lagna':None,'planets':{},'dasha':None,
     'outcome_domain':'career','outcome_positive':False,'outcome_description':'Conspiracy 6/8/12+Rahu',
     'key_pattern':'rahu_conspiracy','key_lesson':'Rahu=conspiracy; 6/8 activation',
     'reasoning_chain':['6th 8th 12th','Rahu deception','Saturn lagna'],'source':'KN Rao - Dasha Nirnay','partial':True},
    {'id':'KNR-CS-055','name':'Ex60 Kidnap+Recovery','lagna':None,'planets':{},'dasha':None,
     'outcome_domain':'health','outcome_positive':None,'outcome_description':'Kidnap 8/12/Rahu; recovery benefic sub',
     'key_pattern':'kidnap_recovery','key_lesson':'Look for recovery; sub-period change=energy shift',
     'reasoning_chain':['8th 12th Rahu','Benefic sub=release'],'source':'KN Rao - Dasha Nirnay','partial':True},
    {'id':'KNR-CS-056','name':'Ex61 Child Death','lagna':None,'planets':{},'dasha':None,
     'outcome_domain':'children','outcome_positive':False,'outcome_description':'Child death: 5th devastated+derived markesh',
     'key_pattern':'5th_child_death','key_lesson':'Derived chart: 5th as child lagna',
     'reasoning_chain':['5th affliction','Jupiter weak','Markesh 6+11'],'source':'KN Rao - Dasha Nirnay','partial':True},
    {'id':'KNR-CS-057','name':'Ex62-64 Promotion/Prosperity','lagna':None,'planets':{},'dasha':None,
     'outcome_domain':'career','outcome_positive':True,'outcome_description':'Promotion 10th; prosperity 2/11; foreign needs both',
     'key_pattern':'foreign_prosperity','key_lesson':'Foreign prosperity needs foreign(9/12/Rahu) AND wealth(2/11)',
     'reasoning_chain':['Promotion: 10th+Jupiter','Prosperity: 2/11','Foreign: 9/12/Rahu+2/11'],'source':'KN Rao - Dasha Nirnay','partial':True},
    {'id':'KNR-CS-058','name':'Ex65 Eyesight Loss','lagna':None,'planets':{},'dasha':None,
     'outcome_domain':'health','outcome_positive':False,'outcome_description':'Blindness: 2/12+Sun/Moon/Venus afflicted',
     'key_pattern':'2_12_eye','key_lesson':'Eyes: 2nd(right) 12th(left) Sun Moon Venus; multiple converge',
     'reasoning_chain':['2nd right 12th left','Sun Moon Venus','Malefic affliction'],'source':'KN Rao - Dasha Nirnay','partial':True},
    {'id':'KNR-CS-059','name':'Ex66-68 Fire Death x3','lagna':None,'planets':{},'dasha':None,
     'outcome_domain':'death','outcome_positive':False,'outcome_description':'Fire death fiery 7/8 three charts',
     'key_pattern':'fire_7_8','key_lesson':'Five fire-death cases establish pattern',
     'reasoning_chain':['Aries/Leo/Sag maraka','Mars Sun','Ketu','Three charts'],'source':'KN Rao - Dasha Nirnay','partial':True},
    {'id':'KNR-CS-060','name':'Ex69 Husband Death','lagna':None,'planets':{},'dasha':None,
     'outcome_domain':'death','outcome_positive':False,'outcome_description':'Husband death 7/8+malefic',
     'key_pattern':'7_8_husband_repeat','key_lesson':'Each confirming case strengthens method',
     'reasoning_chain':['7th 8th Mars/Saturn','Jupiter affliction','Verify'],'source':'KN Rao - Dasha Nirnay','partial':True},
    # ==========================================================================
    # BV RAMAN: Hindu Predictive Astrology (CS-001..034)
    # ==========================================================================
    {'id':'BVR-CS-001','name':'Female Child Death 16 Months','lagna':None,
     'planets':{'Moon':{'house':7},'Venus':{'conjunction':'Saturn,Ketu'},'Saturn':{'aspect_on':'Moon'},'Rahu':{'aspect_on':'Venus'}},
     'dasha':{'md':'Venus','ad':'Venus'},'outcome_domain':'death','outcome_positive':False,
     'outcome_description':'Female infant died within 16 months; Balarishta',
     'key_pattern':'balarishta_dasa_lord_afflicted','key_lesson':'Dasa lord afflicted + Moon in kendra under malefic grip without benefic = Balarishta',
     'reasoning_chain':['Venus dasa at birth for 16 months','Moon in 7th aspected by Saturn no benefic','Venus conjunct Saturn+Ketu aspected by Rahu','Three independent afflictions converge'],
     'source':'BV Raman - Hindu Predictive Astrology','partial':True},
    {'id':'BVR-CS-002','name':'Male Child Death 13 Months','lagna':None,
     'planets':{'Rahu':{'near':'lagna'},'Saturn':{'near':'lagna','aspect_on':'Moon,Sun'},'Moon':{}},
     'dasha':{'md':'Sun'},'outcome_domain':'death','outcome_positive':False,
     'outcome_description':'Male infant died 13th month; Balarishta from triple Saturn affliction',
     'key_pattern':'balarishta_triple_saturn','key_lesson':'Saturn hemming lagna + afflicting Moon + aspecting dasa lord = lethal in infancy',
     'reasoning_chain':['Lagna hemmed by Rahu and Saturn (Papakartari)','Moon afflicted by Saturn','Dasa lord Sun aspected by Saturn','Triple Saturn convergence'],
     'source':'BV Raman - Hindu Predictive Astrology','partial':True},
    {'id':'BVR-CS-003','name':'Male Suffered Childhood Lived 82','lagna':'Taurus',
     'planets':{'Moon':{'conjunction':'Rahu'},'Rahu':{'aspect_from':'Mars,Ketu'},'Jupiter':{'house':'kendra'},'Saturn':{'rashi':'Gemini'},'Mars':{'conjunction':'Ketu'}},
     'dasha':None,'outcome_domain':'health','outcome_positive':True,
     'outcome_description':'Balarishta cancelled by Jupiter in kendra; suffered till 8, lived to 82 (Purnayu)',
     'key_pattern':'balarishta_cancellation_jupiter_kendra','key_lesson':'Jupiter in kendra cancels even multiple Balarishta indicators; suffering still manifests but does not kill',
     'reasoning_chain':['Papakartari on lagna','Moon-Rahu conjunction','Rahu aspected by Mars+Ketu','Jupiter in kendra=cancellation','Suffered till 8 then recovered','Died age 82'],
     'source':'BV Raman - Hindu Predictive Astrology','partial':False},
    {'id':'BVR-CS-004','name':'Mussolini','lagna':'Scorpio',
     'planets':{'Moon':{'rashi':'Taurus'},'Mars':{'rashi':'Taurus'},'Saturn':{'rashi':'Taurus'},'Sun':{'rashi':'Cancer'},'Venus':{'rashi':'Cancer'},'Mercury':{'rashi':'Cancer'},'Jupiter':{'rashi':'Gemini'},'Rahu':{'rashi':'Libra'},'Ketu':{'rashi':'Aries'}},
     'dasha':None,'outcome_domain':'political','outcome_positive':None,
     'outcome_description':'Rose from poverty to greatest man of Europe; sudden downfall and violent end',
     'key_pattern':'scorpio_mars_saturn_rise_fall','key_lesson':'Mars-Saturn conjunction drives spectacular rise but creates conditions for violent fall',
     'reasoning_chain':['Scorpio lagna=transformation','Moon+Mars+Saturn in 7th Taurus','Sun+Venus+Mercury in 9th Cancer','Blacksmith son to ruler of Europe','Same Mars-Saturn=rise AND violent end'],
     'source':'BV Raman - Hindu Predictive Astrology','partial':False},
    {'id':'BVR-CS-005','name':'Prof B Suryanarain Rao','lagna':'Cancer',
     'planets':{'Sun':{'rashi':'Gemini'},'Moon':{'rashi':'Leo'},'Mars':{'rashi':'Gemini'},'Mercury':{'rashi':'Cancer'},'Jupiter':{'rashi':'Cancer'},'Venus':{'rashi':'Gemini'},'Saturn':{'rashi':'Sagittarius'},'Rahu':{'rashi':'Taurus'},'Ketu':{'rashi':'Scorpio'}},
     'dasha':None,'outcome_domain':'career','outcome_positive':True,
     'outcome_description':'Father died age 2; two wives; lost sisters; great career distinction; Jupiter+Mercury in Cancer lagna',
     'key_pattern':'jupiter_cancer_lagna_protection','key_lesson':'Jupiter in own sign in lagna is best gift; cannot prevent karmic losses but ensures native rises above them',
     'reasoning_chain':['Sun+Mars in 12th aspected by Saturn=father died age 2','Venus afflicted=two wives','Jupiter+Mercury in Cancer lagna=extraordinary achievement','Jupiter saves despite afflictions'],
     'source':'BV Raman - Hindu Predictive Astrology','partial':False},
    {'id':'BVR-CS-006','name':'Herbert Hoover','lagna':'Taurus',
     'planets':{'Sun':{'rashi':'Cancer'},'Moon':{'rashi':'Cancer'},'Mars':{'rashi':'Cancer'},'Mercury':{'rashi':'Cancer'},'Jupiter':{'rashi':'Virgo'},'Venus':{'rashi':'Virgo'},'Saturn':{'rashi':'Capricorn','dignity':'own'},'Rahu':{'rashi':'Aries'},'Ketu':{'rashi':'Libra'}},
     'dasha':None,'outcome_domain':'political','outcome_positive':True,
     'outcome_description':'Great politician equal to king; saved Europe from anarchy; humble origin',
     'key_pattern':'saturn_yogakaraka_taurus','key_lesson':'For Taurus lagna Saturn alone produces Rajayoga; in own sign=commoner rises to royalty',
     'reasoning_chain':['Taurus lagna: Saturn most auspicious','Saturn in own sign Capricorn 9th','Four planets in Cancer 3rd','Jupiter+Venus in Virgo 5th'],
     'source':'BV Raman - Hindu Predictive Astrology','partial':False},
    {'id':'BVR-CS-007','name':'Female Smallpox Death 14','lagna':'Taurus',
     'planets':{'Ketu':{'rashi':'Aries'},'Moon':{'rashi':'Taurus'},'Jupiter':{'rashi':'Leo'},'Saturn':{'rashi':'Leo','aspect_on':'lagna,Moon'},'Rahu':{'rashi':'Libra'},'Sun':{'rashi':'Libra'},'Mercury':{'rashi':'Scorpio'},'Venus':{'rashi':'Scorpio'},'Mars':{'rashi':'Sagittarius'}},
     'dasha':None,'outcome_domain':'health','outcome_positive':False,
     'outcome_description':'Smallpox age 8, dropsy, died 14th year',
     'key_pattern':'saturn_aspect_lagna_moon_disease','key_lesson':'Saturn aspecting both lagna and Moon simultaneously=chronic ill health pattern',
     'reasoning_chain':['Saturn in Leo aspects Taurus lagna and Moon','Malefic conjunction in Libra 6th','Smallpox 8th year','Died 14th year'],
     'source':'BV Raman - Hindu Predictive Astrology','partial':False},
    {'id':'BVR-CS-008','name':'Female Widowhood 14','lagna':'Taurus',
     'planets':{'Sun':{'rashi':'Taurus'},'Rahu':{'rashi':'Taurus'},'Venus':{'rashi':'Gemini'},'Mercury':{'rashi':'Gemini'},'Jupiter':{'rashi':'Leo'},'Ketu':{'rashi':'Scorpio'},'Mars':{'rashi':'Aquarius'},'Moon':{'rashi':'Pisces'},'Saturn':{'rashi':'Pisces'}},
     'dasha':None,'outcome_domain':'marriage','outcome_positive':False,
     'outcome_description':'Husband died in 14th year; Mars 12th from Moon=widowhood',
     'key_pattern':'mars_12th_moon_widowhood','key_lesson':'Mars in 12th from Moon is strong widowhood indicator for female charts',
     'reasoning_chain':['Mars in Aquarius, Moon in Pisces','Mars 12th from Moon=widowhood','Husband taken away in 14th year'],
     'source':'BV Raman - Hindu Predictive Astrology','partial':False},
    {'id':'BVR-CS-009','name':'Female Balarishta Death 15 Months','lagna':'Aquarius',
     'planets':{'Jupiter':{'rashi':'Pisces'},'Rahu':{'rashi':'Taurus'},'Moon':{'rashi':'Leo'},'Venus':{'rashi':'Scorpio'},'Saturn':{'rashi':'Scorpio'},'Ketu':{'rashi':'Scorpio'},'Sun':{'rashi':'Sagittarius'},'Mercury':{'rashi':'Sagittarius'},'Mars':{'rashi':'Sagittarius'}},
     'dasha':None,'outcome_domain':'death','outcome_positive':False,
     'outcome_description':'Died 15th month; malefic concentration in 10th-11th without benefic rescue',
     'key_pattern':'balarishta_malefic_concentration','key_lesson':'Malefic concentration in consecutive houses without Jupiter aspect on lagna=Balarishta',
     'reasoning_chain':['Venus+Saturn+Ketu in Scorpio 10th','Sun+Mercury+Mars in Sagittarius 11th','Jupiter in 2nd Pisces not aspecting lagna','No cancellation available'],
     'source':'BV Raman - Hindu Predictive Astrology','partial':False},
    {'id':'BVR-CS-010','name':'British Field Marshal','lagna':'Aquarius',
     'planets':{'Moon':{'rashi':'Pisces'},'Saturn':{'rashi':'Aries'},'Venus':{'rashi':'Cancer'},'Mars':{'rashi':'Libra'},'Sun':{'rashi':'Virgo'},'Jupiter':{'rashi':'Scorpio'},'Mercury':{'rashi':'Virgo'}},
     'dasha':None,'outcome_domain':'career','outcome_positive':True,
     'outcome_description':'Excellent military career; commanded British Army Great War; Earldom 1921; died 1925',
     'key_pattern':'mars_9th_military','key_lesson':'Mars in 9th for Aquarius lagna channels martial energy into distinguished military career',
     'reasoning_chain':['Aquarius lagna, Saturn lord in Aries 3rd courage','Mars in Libra 9th=fortune through authority','Military career+honors+death sequence mapped'],
     'source':'BV Raman - Hindu Predictive Astrology','partial':False},
    {'id':'BVR-CS-011','name':'Archduke Rudolf','lagna':'Taurus',
     'planets':{'Jupiter':{'rashi':'Taurus'},'Saturn':{'rashi':'Cancer'},'Sun':{'rashi':'Leo'},'Ketu':{'rashi':'Leo'},'Venus':{'rashi':'Virgo'},'Mercury':{'rashi':'Virgo'},'Mars':{'rashi':'Scorpio'},'Moon':{'rashi':'Capricorn'},'Rahu':{'rashi':'Aquarius'}},
     'dasha':None,'outcome_domain':'death','outcome_positive':False,
     'outcome_description':'Ill-starred prince; loveless marriage; clandestine life; death from suicide',
     'key_pattern':'mars_7th_own_sign_destruction','key_lesson':'Mars in 7th in own sign (Scorpio) for Taurus lagna destroys marriage; Ketu+Sun in 4th=self-destructive tendencies',
     'reasoning_chain':['Mars in Scorpio 7th own sign=destructive to marriage','Ketu+Sun in Leo 4th=emotional volatility','Moon debilitated in Capricorn 9th','Loveless marriage, clandestine life, suicide'],
     'source':'BV Raman - Hindu Predictive Astrology','partial':False},
    {'id':'BVR-CS-012','name':'Loss of Vision Age 45','lagna':'Pisces',
     'planets':{'Sun':{'rashi':'Pisces'},'Ketu':{'rashi':'Aries'},'Saturn':{'rashi':'Taurus'},'Jupiter':{'rashi':'Gemini'},'Moon':{'rashi':'Virgo'},'Rahu':{'rashi':'Libra'},'Venus':{'rashi':'Capricorn'},'Mercury':{'rashi':'Aquarius'},'Mars':{'rashi':'Aquarius'}},
     'dasha':None,'outcome_domain':'health','outcome_positive':False,
     'outcome_description':'Loss of vision at 45; Mercury+Mars in Aquarius aspected by Saturn=optic nerve damage',
     'key_pattern':'mercury_mars_saturn_aquarius_eyes','key_lesson':'Mercury(nerves)+Mars(inflammation)+Saturn aspect in Aquarius=optic nerve damage',
     'reasoning_chain':['Mercury+Mars in Aquarius','Saturn aspects from Taurus','Aquarius=nervous system','Optic nerve affected','Vision lost age 45'],
     'source':'BV Raman - Hindu Predictive Astrology','partial':False},
    {'id':'BVR-CS-013','name':'Guglielmo Marconi','lagna':'Gemini',
     'planets':{'Moon':{'rashi':'Leo'},'Jupiter':{'rashi':'Virgo'},'Saturn':{'rashi':'Capricorn','dignity':'own'},'Mercury':{'rashi':'Pisces'},'Sun':{'rashi':'Aries','dignity':'exalted'},'Venus':{'rashi':'Taurus'},'Mars':{'rashi':'Taurus'},'Rahu':{'rashi':'Aries'}},
     'dasha':None,'outcome_domain':'career','outcome_positive':True,
     'outcome_description':'Expert physicist; inventor of wireless; revolutionized electric world',
     'key_pattern':'gemini_lagna_exalted_sun_innovation','key_lesson':'Gemini lagna + exalted Sun in 11th=scientific innovation achieving worldly recognition',
     'reasoning_chain':['Gemini lagna=intellectual','Sun exalted in Aries 11th','Saturn own sign Capricorn 8th=deep research','Jupiter in Virgo 4th=analytical mind'],
     'source':'BV Raman - Hindu Predictive Astrology','partial':False},
    {'id':'BVR-CS-014','name':'Carolus Linnaeus','lagna':'Capricorn',
     'planets':{'Venus':{'rashi':'Aries'},'Mercury':{'rashi':'Aries'},'Sun':{'rashi':'Taurus'},'Saturn':{'rashi':'Taurus'},'Mars':{'rashi':'Cancer'},'Jupiter':{'rashi':'Leo'},'Moon':{'rashi':'Aquarius'}},
     'dasha':None,'outcome_domain':'career','outcome_positive':True,
     'outcome_description':'Greatest botanist; binomial nomenclature; Professor 1739; apoplexy 1774; died 1778',
     'key_pattern':'venus_yogakaraka_capricorn','key_lesson':'For Capricorn lagna Venus is most powerful; Venus in 4th=academic distinction',
     'reasoning_chain':['Capricorn lagna','Venus yogakaraka in Aries 4th','Professor of botany','Apoplexy and death in later life'],
     'source':'BV Raman - Hindu Predictive Astrology','partial':False},
    {'id':'BVR-CS-015','name':'Mahatma Gandhi','lagna':'Libra',
     'planets':{'Jupiter':{'rashi':'Aries'},'Rahu':{'rashi':'Cancer'},'Moon':{'rashi':'Cancer'},'Sun':{'rashi':'Virgo'},'Mars':{'rashi':'Libra'},'Venus':{'rashi':'Libra'},'Mercury':{'rashi':'Libra'},'Saturn':{'rashi':'Scorpio'},'Ketu':{'rashi':'Capricorn'}},
     'dasha':None,'outcome_domain':'political','outcome_positive':True,
     'outcome_description':'Great Indian leader; always incarceration; opponent of British rule; great sufferer',
     'key_pattern':'saturn_yogakaraka_libra_suffering','key_lesson':'Rajayoga through Saturn does not mean comfort; creates success through hardship and sacrifice',
     'reasoning_chain':['Libra lagna: Saturn causes Rajayoga','Saturn in Scorpio 2nd','Four planets in lagna','Moon+Rahu in Cancer 10th=agitation in public role','Greatness through suffering'],
     'source':'BV Raman - Hindu Predictive Astrology','partial':False},
    {'id':'BVR-CS-016','name':'Henry Ford','lagna':'Scorpio',
     'planets':{'Moon':{'rashi':'Capricorn'},'Sun':{'rashi':'Cancer'},'Mercury':{'rashi':'Cancer'},'Mars':{'rashi':'Leo'},'Venus':{'rashi':'Virgo'},'Saturn':{'rashi':'Virgo'},'Jupiter':{'rashi':'Libra'},'Rahu':{'rashi':'Scorpio'},'Ketu':{'rashi':'Taurus'}},
     'dasha':None,'outcome_domain':'wealth','outcome_positive':True,
     'outcome_description':'World richest man; restless, active, energetic; conflicting traits',
     'key_pattern':'11th_venus_saturn_wealth','key_lesson':'Venus+Saturn in 11th for Scorpio lagna=enormous wealth; Mars in Leo 10th=relentless industrial activity',
     'reasoning_chain':['Scorpio lagna','Venus+Saturn in Virgo 11th=massive income','Mars in Leo 10th=industrial drive','Jupiter in Libra 12th=unusual wealth yoga'],
     'source':'BV Raman - Hindu Predictive Astrology','partial':False},
    {'id':'BVR-CS-017','name':'Female Widowhood 19','lagna':'Virgo',
     'planets':{'Mars':{'rashi':'Pisces'},'Rahu':{'rashi':'Pisces'},'Venus':{'rashi':'Aries'},'Sun':{'rashi':'Taurus'},'Mercury':{'rashi':'Taurus'},'Saturn':{'rashi':'Taurus'},'Moon':{'rashi':'Gemini'},'Ketu':{'rashi':'Virgo'},'Jupiter':{'rashi':'Sagittarius'}},
     'dasha':None,'outcome_domain':'marriage','outcome_positive':False,
     'outcome_description':'Husband died in 19th year; Mars+Rahu in 8th bhava=widowhood',
     'key_pattern':'mars_rahu_8th_widowhood','key_lesson':'Mars+Rahu in 8th (longevity of spouse) cuts short husband life',
     'reasoning_chain':['Mars+Rahu in Pisces 7th/8th bhava','8th=longevity of husband (2nd from 7th)','Husband died 19th year'],
     'source':'BV Raman - Hindu Predictive Astrology','partial':False},
    {'id':'BVR-CS-018','name':'Female Father Died 9 Months','lagna':'Aquarius',
     'planets':{'Ketu':{'rashi':'Aries'},'Sun':{'rashi':'Leo'},'Mercury':{'rashi':'Leo'},'Jupiter':{'rashi':'Leo'},'Saturn':{'rashi':'Leo'},'Venus':{'rashi':'Virgo','dignity':'debilitated'},'Rahu':{'rashi':'Libra'},'Mars':{'rashi':'Scorpio'},'Moon':{'rashi':'Aquarius'}},
     'dasha':None,'outcome_domain':'death','outcome_positive':False,
     'outcome_description':'Father died within 9 months; Venus debilitated in 9th + Sun conjunct Saturn',
     'key_pattern':'father_death_9th_sun_saturn','key_lesson':'Father death needs BOTH 9th house/lord afflicted AND Sun karaka afflicted',
     'reasoning_chain':['Venus debilitated in Virgo 8th (9th from lagna is debilitated)','Sun conjunct Saturn in Leo','Dual affliction: 9th lord debilitated + Sun karaka with Saturn','Father died within 9 months'],
     'source':'BV Raman - Hindu Predictive Astrology','partial':False},
    {'id':'BVR-CS-019','name':'Medical Man Father Died 7','lagna':'Libra',
     'planets':{'Saturn':{'rashi':'Aries'},'Rahu':{'rashi':'Taurus'},'Venus':{'rashi':'Leo'},'Moon':{'rashi':'Leo'},'Mars':{'rashi':'Virgo'},'Sun':{'rashi':'Virgo'},'Mercury':{'rashi':'Virgo'},'Jupiter':{'rashi':'Virgo'},'Ketu':{'rashi':'Scorpio'}},
     'dasha':None,'outcome_domain':'death','outcome_positive':False,
     'outcome_description':'Medical man lost father 7th year; Sun approaching debilitation in Virgo',
     'key_pattern':'sun_approaching_debilitation_father','key_lesson':'Even Sun approaching debilitation (sign before Libra) weakens father karaka',
     'reasoning_chain':['Sun in Virgo approaching Libra debilitation','Karaka for father weakened','Father lost age 7','Medical man, eccentric'],
     'source':'BV Raman - Hindu Predictive Astrology','partial':False},
    {'id':'BVR-CS-020','name':'Male 15 Children High Position','lagna':'Pisces',
     'planets':{'Rahu':{'rashi':'Aries'},'Moon':{'rashi':'Cancer','dignity':'own'},'Sun':{'rashi':'Leo'},'Mars':{'rashi':'Leo'},'Mercury':{'rashi':'Leo'},'Jupiter':{'rashi':'Virgo'},'Venus':{'rashi':'Libra'},'Ketu':{'rashi':'Libra'},'Saturn':{'rashi':'Capricorn','dignity':'own'}},
     'dasha':None,'outcome_domain':'children','outcome_positive':True,
     'outcome_description':'15 living children; high position; fair wife; planets in own signs',
     'key_pattern':'planets_own_sign_stability','key_lesson':'Planets in own signs (swakshetra) provide stability; Moon own sign=many surviving children; Saturn own sign=longevity',
     'reasoning_chain':['Pisces lagna Mars yogakaraka','Saturn in Capricorn own sign=longevity','Moon in Cancer own sign=nurturing','Mars+Sun+Mercury in Leo 6th=victory','15 children living'],
     'source':'BV Raman - Hindu Predictive Astrology','partial':False},
    {'id':'BVR-CS-021','name':'Female Triple Loss','lagna':'Pisces',
     'planets':{'Jupiter':{'rashi':'Aries'},'Moon':{'rashi':'Cancer'},'Rahu':{'rashi':'Leo'},'Mars':{'rashi':'Libra'},'Mercury':{'rashi':'Sagittarius'},'Sun':{'rashi':'Capricorn'},'Saturn':{'rashi':'Capricorn'},'Venus':{'rashi':'Aquarius'},'Ketu':{'rashi':'Aquarius'}},
     'dasha':None,'outcome_domain':'death','outcome_positive':False,
     'outcome_description':'Father died 7th year, mother died 16th year, husband died 19th year; triple karaka affliction',
     'key_pattern':'independent_karaka_loss_signatures','key_lesson':'Each relationship has own karaka and house analysis; multiple independent loss signatures operate independently',
     'reasoning_chain':['Sun+Saturn=father dies age 7','Moon affliction Rahu 2nd from Moon=mother dies 16','Mars in Libra 8th=husband dies 19','Same chart contains three independent loss patterns'],
     'source':'BV Raman - Hindu Predictive Astrology','partial':False},
    {'id':'BVR-CS-022','name':'Female Balarishta Death 6 Months','lagna':'Capricorn',
     'planets':{'Sun':{'rashi':'Pisces'},'Mercury':{'rashi':'Pisces'},'Moon':{'rashi':'Aries'},'Venus':{'rashi':'Aries'},'Rahu':{'rashi':'Aries'},'Jupiter':{'rashi':'Taurus'},'Ketu':{'rashi':'Libra'},'Saturn':{'rashi':'Sagittarius'},'Mars':{'rashi':'Aquarius'}},
     'dasha':None,'outcome_domain':'death','outcome_positive':False,
     'outcome_description':'Died 6th month; malefics in 12th from Moon AND 2nd/12th from lagna',
     'key_pattern':'balarishta_12th_from_both','key_lesson':'Malefics in 12th from Moon AND 2nd/12th from lagna simultaneously=lethal Balarishta',
     'reasoning_chain':['Moon in Aries, 12th=Pisces has Sun+Mercury','Lagna Capricorn: 12th Sagittarius has Saturn; 2nd Aquarius has Mars','Moon with Venus+Rahu','Died 6th month'],
     'source':'BV Raman - Hindu Predictive Astrology','partial':False},
    {'id':'BVR-CS-023','name':'Prof B Suryanarain Rao Full Life','lagna':'Taurus',
     'planets':{'Moon':{'rashi':'Aries'},'Rahu':{'rashi':'Aries'},'Saturn':{'rashi':'Gemini'},'Mars':{'rashi':'Libra'},'Ketu':{'rashi':'Libra'},'Venus':{'rashi':'Sagittarius'},'Sun':{'rashi':'Aquarius'},'Mercury':{'rashi':'Aquarius'},'Jupiter':{'rashi':'Aquarius'}},
     'dasha':None,'outcome_domain':'career','outcome_positive':True,
     'outcome_description':'World greatest astrologer/historian/author; two wives; advanced yogi; died 82',
     'key_pattern':'jupiter_kendra_balarishta_cancel_to_greatness','key_lesson':'Same chart that nearly killed in infancy produced greatest astrologer; Jupiter kendra saves and elevates',
     'reasoning_chain':['Same chart as BVR-CS-003','Jupiter in kendra cancelled Balarishta','Mercury+Jupiter in Aquarius 10th=astrology career','Revived astrology in India','Died age 82 Purnayu'],
     'source':'BV Raman - Hindu Predictive Astrology','partial':False},
    {'id':'BVR-CS-024','name':'Horary Marriage Question','lagna':None,
     'planets':{'Mercury':{'rashi':'Taurus'},'Venus':{'rashi':'Taurus','conjunction':'Mercury'},'Jupiter':{'rashi':'Cancer','dignity':'exalted'}},
     'dasha':None,'outcome_domain':'marriage','outcome_positive':True,
     'outcome_description':'Prasna: querist will marry early; fair bride through pious man; all three factors strong',
     'key_pattern':'prasna_triple_strength','key_lesson':'In Prasna check lagna lord + house lord + karaka; all strong and connected=success',
     'reasoning_chain':['Prasna lagna Virgo, lord Mercury in Taurus friend sign','7th lord Jupiter exalted in Cancer','Venus with Mercury=karaka supports lagna lord','Early marriage, fair bride, pious intermediary'],
     'source':'BV Raman - Hindu Predictive Astrology','partial':True},
    {'id':'BVR-CS-025','name':'Transit Death Analysis','lagna':None,
     'planets':{'Saturn':{'transit':'12th','ashtakavarga_bindus':3},'Mars':{'transit':'8th','ashtakavarga_bindus':4}},
     'dasha':None,'outcome_domain':'death','outcome_positive':False,
     'outcome_description':'Death when Saturn in 12th(3 bindus) + Mars in 8th simultaneously; Vedha neutralized good transits',
     'key_pattern':'transit_death_saturn12_mars8','key_lesson':'Saturn-12th + Mars-8th simultaneously=lethal; Vedha neutralizes apparently good transits',
     'reasoning_chain':['Sun 11th good no vedha','Moon 11th good BUT Mars 8th causes vedha=BAD','Mars 8th bad','Mercury 11th good BUT Saturn 12th vedha=BAD','Jupiter 9th good','Venus 1st good BUT Mars 8th vedha=BAD','Saturn 12th only 3 bindus=exceedingly bad','Only Jupiter+Sun truly good; death resulted'],
     'source':'BV Raman - Hindu Predictive Astrology','partial':True},
    {'id':'BVR-CS-026','name':'Unknown Birth Time Reconstruction','lagna':None,
     'planets':{},'dasha':None,'outcome_domain':'career','outcome_positive':None,
     'outcome_description':'Prasna chart reconstructed entire birth data: year, month, day, time from horary query',
     'key_pattern':'prasna_birth_reconstruction','key_lesson':'Prasna chart can reconstruct birth chart from scratch using Dwadasamsa, body part, drekkana, and cycle',
     'reasoning_chain':['Query in first half=Uttarayana','4th Dwadasamsa=Jupiter in 4th from Prasna lagna','Touched thighs=3rd cycle=27 years','Drekkana ruler=birth season','Minutes calculation=29 days passed','Birth at 10.12 ghatis after sunrise'],
     'source':'BV Raman - Hindu Predictive Astrology','partial':True},
    {'id':'BVR-CS-027','name':'Ashtakavarga Longevity Calculation','lagna':None,
     'planets':{'Sun':{'rashi':'Cancer'},'Moon':{'rashi':'Taurus'},'Saturn':{'rashi':'Taurus'},'Mercury':{'rashi':'Leo'},'Venus':{'rashi':'Leo'},'Mars':{'rashi':'Leo'},'Jupiter':{'rashi':'Scorpio'}},
     'dasha':None,'outcome_domain':'death','outcome_positive':None,
     'outcome_description':'Ashtakavarga longevity=44.87 years but BVR says system not satisfactory alone',
     'key_pattern':'ashtakavarga_longevity_caveat','key_lesson':'Ashtakavarga longevity mathematically elegant but practically unreliable alone; always cross-check maraka',
     'reasoning_chain':['Rasi+Graha Gunakara calculated','Raw years summed','Reductions for above-horizon planets','Total 48.98 lunar=44.87 solar','BVR caveat: not satisfactory in practice','Must cross-check with maraka planets'],
     'source':'BV Raman - Hindu Predictive Astrology','partial':False},
    {'id':'BVR-CS-028','name':'Illness 22 Son 23','lagna':None,
     'planets':{},'dasha':None,'outcome_domain':'health','outcome_positive':None,
     'outcome_description':'Malaria at 22 confirmed via Sarvashtakavarga; son/start at 23 via benefic bindus',
     'key_pattern':'sarvashtakavarga_event_timing','key_lesson':'Sarvashtakavarga totals reduced by 12 give specific years; malefic positions=illness years, benefic=fortune years',
     'reasoning_chain':['Saturn+Ascendant+Mars bindus 33+26+23=82','82-60=22=illness year','Malaria 15 days confirmed','Benefic house bindus=47-24=23=son year'],
     'source':'BV Raman - Hindu Predictive Astrology','partial':True},
    {'id':'BVR-CS-029','name':'Miss EA New York Arthritis','lagna':None,
     'planets':{'Mercury':{'house':6},'Saturn':{'house':6},'Mars':{'house':6},'Rahu':{'aspect_on':'6th house'}},
     'dasha':None,'outcome_domain':'health','outcome_positive':False,
     'outcome_description':'Chronic arthritis 25+ years; Mercury+Saturn+Mars in 6th aspected by Rahu',
     'key_pattern':'arthritis_formula','key_lesson':'Mercury(nerves)+Saturn(chronicity)+Mars(inflammation) in 6th + Rahu aspect=chronic arthritis',
     'reasoning_chain':['Mercury in 6th=nerve involvement','Saturn in 6th=chronic degenerative','Mars in 6th=inflammation','Rahu aspect=unusual/persistent','25+ years arthritis'],
     'source':'BV Raman - Hindu Predictive Astrology','partial':True},
    {'id':'BVR-CS-030','name':'Muhurtha Interview Success','lagna':None,
     'planets':{},'dasha':None,'outcome_domain':'career','outcome_positive':True,
     'outcome_description':'Interview successful; Tara Bala remainder 4=Kshema (prosperity)',
     'key_pattern':'tara_bala_kshema','key_lesson':'Tara Bala: count birth to day constellation, divide by 9; remainders 2,4,6,8,9=favorable',
     'reasoning_chain':['Birth star Mrigasira','Day star Uttarabhadra','Count=22, 22/9=remainder 4','4=Kshema=prosperity','Business successful'],
     'source':'BV Raman - Hindu Predictive Astrology','partial':True},
    {'id':'BVR-CS-031','name':'Muhurtha Business Panchaka','lagna':None,
     'planets':{},'dasha':None,'outcome_domain':'career','outcome_positive':False,
     'outcome_description':'Business timing unfavorable; Panchaka remainder 2=Vahni (fire danger)',
     'key_pattern':'panchaka_unfavorable','key_lesson':'Panchaka: lunar days+constellations+signs+weekday; remainders 1,2,4,6,8=bad',
     'reasoning_chain':['Lunar 13+constellation 9+sign 6+weekday 1=29','29/9=remainder 2','2=Vahni=fire danger','Time not favorable'],
     'source':'BV Raman - Hindu Predictive Astrology','partial':True},
    {'id':'BVR-CS-032','name':'Mundane Eclipse WWI','lagna':None,
     'planets':{},'dasha':None,'outcome_domain':'political','outcome_positive':False,
     'outcome_description':'Two eclipses within 14 days March 1914 predicted WWI; assassination of prince; war August 1914',
     'key_pattern':'double_eclipse_war','key_lesson':'Double eclipses within 14 days=national troubles, assassinations, war; sign gives affected country',
     'reasoning_chain':['Two eclipses March 1914 within 14 days','Prof Rao predicted Great War and assassination of prince','WWI began August 1914','Sign of eclipse=affected region'],
     'source':'BV Raman - Hindu Predictive Astrology','partial':True},
    {'id':'BVR-CS-033','name':'Mundane Roosevelt Election','lagna':None,
     'planets':{},'dasha':None,'outcome_domain':'political','outcome_positive':True,
     'outcome_description':'Solar eclipse 1932 predicted Roosevelt election; also predicted 3rd term 1940',
     'key_pattern':'eclipse_leadership_change','key_lesson':'Solar eclipses predict leadership changes; affected country depends on eclipse sign',
     'reasoning_chain':['Solar eclipse 1932 affecting US','Roosevelt election predicted Sept 1932','Third term predicted Sept 1940','Sign-country correspondence'],
     'source':'BV Raman - Hindu Predictive Astrology','partial':True},
    {'id':'BVR-CS-034','name':'Mundane Lunation Effect Nations','lagna':None,
     'planets':{},'dasha':None,'outcome_domain':'political','outcome_positive':None,
     'outcome_description':'Same lunation in Aries+Saturn+Mars affects countries differently based on which house it falls in',
     'key_pattern':'mundane_differential_impact','key_lesson':'Same planetary event produces different effects for different nations based on house from national ascendant',
     'reasoning_chain':['Lunation in Aries with Saturn+Mars','For Aries countries: public ill-health, cabinet chaos','For 10th house countries: death of monarch','For 2nd house countries: financial depression','Same event, different houses, different effects'],
     'source':'BV Raman - Hindu Predictive Astrology','partial':True},
    # ==========================================================================
    # SANJAY RATH: Crux of Vedic Astrology + Vimsottari & Udu Dasas (CS-001..032)
    # ==========================================================================
    {'id':'SR-CS-001','name':'Birth Time Rectification Male','lagna':'Aquarius',
     'planets':{'Venus':{'rashi':'Aries','house':11},'Saturn':{'aspect_on':'3rd house'},'Sun':{'rashi':'Taurus','conjunction':'Moon'},'Moon':{'rashi':'Taurus','dignity':'exalted'}},
     'dasha':None,'outcome_domain':'death','outcome_positive':False,
     'outcome_description':'Birth time rectified from 30-min to 3-min window using D-1, D-3, D-9, D-7 progressively; father death validated',
     'key_pattern':'multi_divisional_rectification','key_lesson':'Birth time rectification requires multiple divisional charts in sequence; chara karakas provide specificity house lords cannot',
     'reasoning_chain':['Aquarius lagna certain from range','AL in Gemini, co-borns confirmed','Drekkana narrows via BK Venus','Navamsa narrows via Upapada+DK Mercury affliction','Saptamsa fixes via children analysis','Kunda correction finalizes','Father death validates'],
     'source':'Sanjay Rath - Crux of Vedic Astrology','partial':False},
    {'id':'SR-CS-002','name':'Swami Vivekananda Longevity','lagna':'Sagittarius',
     'planets':{'Jupiter':{'rashi':'Sagittarius','role':'lagna lord'},'Moon':{'rashi':'Virgo','role':'8th lord'},'Saturn':{'rashi':'Virgo','conjunction':'Moon'},'Sun':{'rashi':'Sagittarius','role':'Atmakaraka'}},
     'dasha':{'md':'Sun','ad':'Moon'},'outcome_domain':'death','outcome_positive':False,
     'outcome_description':'Died age 39 in Sun-Moon dasa; middle life (36-72) after Yoga Vipareetam reversed short life reading',
     'key_pattern':'yoga_vipareetam_ak_lagna','key_lesson':'AK in lagna reverses longevity but at karmic cost (early loss of father/Guru)',
     'reasoning_chain':['Method of pairs: 2/3 short life','AK Sun in lagna=Yoga Vipareetam','Short reversed to middle life','Kakshya Hrasa via Saturn-Moon conjunction','Death in Sun-Moon: Sun gave sanyas, Moon 8th lord from lagna and AK','Died age 39 within 36-72 range'],
     'source':'Sanjay Rath - Crux of Vedic Astrology','partial':False},
    {'id':'SR-CS-003','name':'Chandraswami','lagna':'Cancer',
     'planets':{'Saturn':{'rashi':'Leo','house':2},'Mars':{'rashi':'Leo','house':2,'role':'5th/10th lord'},'Jupiter':{'rashi':'Capricorn','house':7,'dignity':'debilitated','conjunction':'Moon'},'Moon':{'rashi':'Capricorn','conjunction':'Jupiter'},'Rahu':{'rashi':'Pisces','house':9},'Mercury':{'role':'Atmakaraka'}},
     'dasha':None,'outcome_domain':'wealth','outcome_positive':None,
     'outcome_description':'Wealth from tantric practice, donations, foreign associates; imprisonment from Bandhan Yoga',
     'key_pattern':'bandhan_yoga_rahu_ketu_axis','key_lesson':'Gajakesari yoga has dual potential: rise through Jupiter AND downfall through Rahu; Hora Lagna essential for wealth',
     'reasoning_chain':['Saturn+Mars in 2nd Leo','7th lord in 2nd=wealth from abroad','Hora Lagna Pisces 9th with Rahu=overseas wealth','Jupiter debilitated 7th with Moon=Gajakesari','Equal planets 5th and 9th=Bandhan Yoga','Mercury AK=mercurial soul identity'],
     'source':'Sanjay Rath - Crux of Vedic Astrology','partial':False},
    {'id':'SR-CS-004','name':'Property Argala Analysis','lagna':None,
     'planets':{'Mercury':{'house':5,'dignity':'exalted','role':'2nd/5th lord'},'Sun':{'house':3,'role':'4th lord','conjunction':'Ketu'},'Ketu':{'house':3},'Venus':{'house':2,'role':'Chaturthamsa lagna lord'}},
     'dasha':None,'outcome_domain':'wealth','outcome_positive':True,
     'outcome_description':'Four large factory spaces in Okhla Delhi; one for business, three leased; argala mechanics explain',
     'key_pattern':'argala_property_tradeoff','key_lesson':'Argala and obstruction show real-world trade-offs; 3rd obstructing 5th argala on 4th=contracts prevent personal use of property',
     'reasoning_chain':['4th house argala from exalted Mercury=properties','Mercury exalted 5th=ownership guaranteed, commercial value','4th lord Sun+Ketu in 3rd=hiring out factory space','3rd obstructs 5th argala=leasing period','Venus Chaturthamsa lord in 2nd=wealth-oriented view'],
     'source':'Sanjay Rath - Crux of Vedic Astrology','partial':True},
    {'id':'SR-CS-005','name':'Twins Birth Female','lagna':None,
     'planets':{},'dasha':{'md':'Saturn','ad':'Jupiter','pd':'Mars'},
     'outcome_domain':'children','outcome_positive':True,
     'outcome_description':'Twin boys born Dec 20 1980 in Saturn-Jupiter-Mars; Saptamsa analysis with Scorpio involvement',
     'key_pattern':'saptamsa_twins_scorpio','key_lesson':'Saptamsa is primary for children; dual planets and Scorpio indicate twins; Moon strong in female chart overrides 6th lord destruction',
     'reasoning_chain':['Saptamsa Aries lagna','7th lord in Scorpio=twins sign','5th lord aspected by Mercury dual planet+Rahu','Moon strength in female chart=protection override','Saturn-Jupiter-Mars dasa=delivery','Taurus Moon sign=quadrant to D-7 Moon Leo'],
     'source':'Sanjay Rath - Crux of Vedic Astrology','partial':True},
    {'id':'SR-CS-006','name':'Sigmund Freud','lagna':None,
     'planets':{'Venus':{'house':7,'role':'Chara Dara Karaka'},'Mercury':{'conjunction':'Moon','role':'9th/10th lord'},'Moon':{'house':8,'role':'10th lord'}},
     'dasha':{'md':'Saturn'},'outcome_domain':'career','outcome_positive':True,
     'outcome_description':'Groundbreaking work on sexuality/psychology; Dharma-Karmadhipati yoga in 8th; navamsa lagna lord+AK=powerful Rajyoga',
     'key_pattern':'navamsa_lagna_lord_ak_rajyoga','key_lesson':'Navamsa link between lagna lord and Atmakaraka is most powerful Rajyoga; research signs (Scorpio)=hidden/taboo fields',
     'reasoning_chain':['5th lord in 7th with Venus DK=sex/psychology','Mercury+Moon 9th/10th lords in 8th=Dharma-Karmadhipati in research','Navamsa: Aquarius lagna lord Saturn with AK Sun in Scorpio 10th','Saturn dasa=all planets favorable','Dasamsa confirms'],
     'source':'Sanjay Rath - Crux of Vedic Astrology','partial':True},
    {'id':'SR-CS-007','name':'Female Epilepsy','lagna':None,
     'planets':{'Venus':{'house':12,'role':'lagna lord,Atmakaraka'}},
     'dasha':None,'outcome_domain':'health','outcome_positive':False,
     'outcome_description':'Epilepsy worsened in Sagittarius dasa; remedy through Mahamrityunjaya mantra; Shoola dasa aspects Arudha Lagna',
     'key_pattern':'shoola_dasa_arudha_suffering','key_lesson':'Shoola dasa signs aspecting AL bring death-like suffering; remedies determined by house involved in affliction',
     'reasoning_chain':['Venus lagna lord+AK in 12th=hospital connection','Sagittarius dasa aspects badhak lord and Mrityupada','5th house combination=remedy through prayer','Shoola dasa sign aspecting AL Pisces=suffering','Mahamrityunjaya mantra prescribed'],
     'source':'Sanjay Rath - Crux of Vedic Astrology','partial':True},
    {'id':'SR-CS-008','name':'Female Short Longevity','lagna':'Pisces',
     'planets':{'Jupiter':{'rashi':'Capricorn','dignity':'debilitated','role':'lagna lord'},'Rahu':{'rashi':'Sagittarius','dignity':'debilitated'},'Venus':{'house':7,'dignity':'debilitated','role':'3rd/8th lord'},'Saturn':{'house':'kendra'}},
     'dasha':None,'outcome_domain':'death','outcome_positive':False,
     'outcome_description':'Very short life; lagna lord+8th lord both debilitated; neechabhanga only partial rescue',
     'key_pattern':'double_debilitated_lords_short_life','key_lesson':'Neechabhanga is partial not complete; lagna lord+8th lord both debilitated=severely compromised longevity even with cancellation',
     'reasoning_chain':['Jupiter lagna lord debilitated Capricorn','Venus 3rd/8th lord debilitated in 7th','Rahu debilitated Sagittarius 12th from Jupiter','Jupiter gets neechabhanga from Saturn in kendra','Partial rescue only','AL Scorpio, Hora Lagna Libra, Mrityupada Leo'],
     'source':'Sanjay Rath - Crux of Vedic Astrology','partial':False},
    {'id':'SR-CS-009','name':'Aishwarya Rai','lagna':None,
     'planets':{'Jupiter':{'role':'trine to lagna'},'Venus':{'role':'trine to navamsa lagna'},'Rahu':{'role':'Atmakaraka','degree':'6deg11'}},
     'dasha':None,'outcome_domain':'career','outcome_positive':True,
     'outcome_description':'Won Miss World; Jaya Yoga=beauty; Darapada A7 in Scorpio=chief competitor Sushmita Sen Scorpio rising',
     'key_pattern':'darapada_competitor_identification','key_lesson':'A7 (not A6) for beauty competition (peers not enemies); arudha padas literally show competitor ascendant',
     'reasoning_chain':['Jupiter+Venus in trines=Jaya Yoga=beauty','A7 in Scorpio=competitor has Scorpio lagna','Sushmita Sen born Scorpio ascendant=confirmed','Rahu AK at 6deg11','A10 in Aries','AL in Capricorn'],
     'source':'Sanjay Rath - Crux of Vedic Astrology','partial':True},
    {'id':'SR-CS-010','name':'Neil Armstrong','lagna':'Taurus',
     'planets':{'Moon':{'rashi':'Sagittarius','house':8},'Saturn':{'rashi':'Sagittarius','role':'Yogakaraka,AL lord'},'Jupiter':{'role':'12th lord from AL'},'Venus':{'role':'lagna lord'},'Ketu':{'aspect_on':'Mars'}},
     'dasha':{'md':'Moon','ad':'Ketu','pd':'Venus'},'outcome_domain':'career','outcome_positive':True,
     'outcome_description':'Moon landing July 20 1969 in Moon-Ketu-Venus; 12th from AL=fame from long journeys; Gajakesari overrides difficult Moon',
     'key_pattern':'12th_from_al_fame_journey','key_lesson':'12th from AL shows activity causing fame; Gajakesari overrides difficult Moon placement; D-10 and D-16 confirm',
     'reasoning_chain':['AL Capricorn, 12th=Sagittarius has Moon+Saturn','Saturn yogakaraka+AL lord with Moon=undying fame','12th house=fame from long journeys','Moon-Ketu-Venus dasa for landing','D-10: Moon 9th aspecting 12th','D-16: Moon 7th lord in lagna','Gajakesari rescues Moon dasa'],
     'source':'Sanjay Rath - Crux of Vedic Astrology','partial':False},
    {'id':'SR-CS-011','name':'PV Narasimha Rao','lagna':None,
     'planets':{'Mars':{'house':10,'role':'in D-10 lagna'},'Jupiter':{'house':12,'role':'7th lord,badhakesh'},'Mercury':{'house':10,'dignity':'own','role':'lagnesh of BJP'},'Sun':{'conjunction':'Mars','role':'12th lord'}},
     'dasha':None,'outcome_domain':'political','outcome_positive':None,
     'outcome_description':'PM rise via Vipareeta Rajyoga; fall when Saturn transited A10 and AL; cross-chart AK analysis',
     'key_pattern':'saturn_transit_a10_al_political','key_lesson':'Saturn transit over A10 and AL is primary indicator of political rise/fall; cross-chart AK reveals power mechanics',
     'reasoning_chain':['Badhakesh Jupiter in 12th=removes obstructions','Mars in 10th D-10 with Rahu=PM in Mars dasa','Vipareeta Rajyoga: 12th lord Sun+3rd/8th lord Mars','Bhadra Mahapurush Mercury 10th=stability from opposition','Saturn transit Janma Rasi+A10 Pisces=Congress defeated','Saturn leaving Moon+A10=better days'],
     'source':'Sanjay Rath - Crux of Vedic Astrology','partial':True},
    {'id':'SR-CS-012','name':'Secret Service Officer','lagna':'Scorpio',
     'planets':{'Mars':{'rashi':'Leo','house':10,'role':'lagna lord,Atmakaraka'},'Mercury':{'role':'8th lord'},'Rahu':{'role':'clandestine ops'},'Sun':{'house':12,'conjunction':'Ketu','role':'10th lord'},'Venus':{'conjunction':'Sun,Ketu','role':'7th/12th lord'}},
     'dasha':{'md':'Rahu','ad':'Venus'},'outcome_domain':'career','outcome_positive':True,
     'outcome_description':'Career in intelligence/secret service; Rahu-Saturn Scorpio in D-10=secret service; joined in Rahu-Venus',
     'key_pattern':'rahu_saturn_scorpio_d10_secret','key_lesson':'Rahu-Saturn in Scorpio D-10=secret service; Ketu-Saturn Pisces D-10=spiritual teaching; nodes differentiate',
     'reasoning_chain':['Mars lagna lord+AK in 10th Leo=security services','10th lord Sun in 12th with Ketu=counter-intelligence','Venus 7th/12th lord with Sun+Ketu=espionage','D-10: Saturn+Rahu Scorpio dominates arthatrikona','Rahu-Venus dasa=joined service','Direction from D-10 9th house planets'],
     'source':'Sanjay Rath - Crux of Vedic Astrology','partial':False},
    {'id':'SR-CS-013','name':'Swami Asutosh TM Teacher','lagna':None,
     'planets':{'Ketu':{'house':10},'Saturn':{'near':'lagna'},'Mercury':{'role':'Atmakaraka','degree':'29deg40','note':'vargottama Sagittarius'}},
     'dasha':None,'outcome_domain':'spiritual','outcome_positive':True,
     'outcome_description':'Transcendental Meditation teacher; Maharishi Mahesh Yogi connection; Ketu in 10th D-10=meditation career',
     'key_pattern':'ketu_10th_d10_spiritual','key_lesson':'Ketu dominating D-10 arthatrikona=spiritual career; Upapada lord in 8th=renunciation not marriage',
     'reasoning_chain':['Ketu in 10th=meditation/dhyana','Saturn near lagna=traditional learning','D-10: Saturn+Ketu Pisces=TM teaching','Compare SR-CS-012: Saturn+Rahu Scorpio=secret service','Mercury AK vargottama=powerful spiritual Guru','Upapada in Sagittarius lord Jupiter 8th=renunciation','AL Aquarius=very spiritual'],
     'source':'Sanjay Rath - Crux of Vedic Astrology','partial':True},
    {'id':'SR-CS-014','name':'Business Tycoon Golf Course','lagna':None,
     'planets':{'Saturn':{'position':'8th from Rahu'},'Jupiter':{'position':'6th from AL'}},
     'dasha':None,'outcome_domain':'career','outcome_positive':True,
     'outcome_description':'Service to business transition; golf course venture; 11th from AL=Virgo(garden/turf) with Mars+Rahu+Sun',
     'key_pattern':'11th_from_al_income_source','key_lesson':'Narayan dasa superior to Vimsottari for major life direction changes; 11th from AL literally describes income type',
     'reasoning_chain':['Saturn 8th from Rahu=differences with superiors','Jupiter+Saturn 6th from AL=Pravrajya+Rajyoga','11th from AL Virgo=garden/turf with Mars=outdoor sport','Rahu=foreign game, Sun=rich/powerful','Golf course in outskirts of Delhi','Narayan dasa Pisces Oct 1981=left job'],
     'source':'Sanjay Rath - Crux of Vedic Astrology','partial':True},
    {'id':'SR-CS-015','name':'Marriage Analysis Mars 7th','lagna':None,
     'planets':{'Mars':{'house':7}},'dasha':None,'outcome_domain':'marriage','outcome_positive':False,
     'outcome_description':'Mars in 7th=sorrow in married life, short-lived spouse; Upapada affliction=spouse mental disturbance',
     'key_pattern':'mars_7th_upapada_parallel','key_lesson':'Always check BOTH 7th house (Parashari) AND Upapada (Jaimini) for marriage; both manifest',
     'reasoning_chain':['Mars 7th=sorrow, papa-argala on 4th','Even with Jupiter/Saturn aspect spouse lives but bad behavior','Mars 9th from 11th=relationships end quickly','Upapada afflicted=spouse mental disturbance','Jupiter in 7th=spouse learned','Venus in 7th=strange appetites'],
     'source':'Sanjay Rath - Crux of Vedic Astrology','partial':True},
    {'id':'SR-CS-016','name':'Narayan Dasa Political Rise','lagna':None,
     'planets':{'Saturn':{'role':'lord of AL'},'Moon':{'role':'9th lord'},'Sun':{'role':'10th lord'},'Jupiter':{'rashi':'Pisces'}},
     'dasha':None,'outcome_domain':'political','outcome_positive':True,
     'outcome_description':'Political rise when Narayan dasa sign aligned with AL, A7, A10 simultaneously',
     'key_pattern':'narayan_dasa_triple_arudha','key_lesson':'Political Rajyoga requires convergence across AL, A7, A10; single arudha alignment insufficient',
     'reasoning_chain':['Narayan dasa Cancer with Saturn lord of AL','Moon 9th lord+Sun 10th lord aspect=Rajyoga','Sign in quadrants to AL and A7','Trines to A10 and Jupiter Pisces','Multiple arudha convergence confirms manifestation'],
     'source':'Sanjay Rath - Crux of Vedic Astrology','partial':True},
    {'id':'SR-CS-017','name':'Sushmita Sen vs Aishwarya Rai','lagna':None,
     'planets':{},'dasha':None,'outcome_domain':'career','outcome_positive':True,
     'outcome_description':'Comparative beauty pageant analysis; A7 literally reveals competitor ascendant',
     'key_pattern':'a7_competitor_ascendant','key_lesson':'Jaimini arudha padas have literal predictive power; A7 points to specific chart features of related persons',
     'reasoning_chain':['Aishwarya A7 in Scorpio','Sushmita is Scorpio rising=confirmed','A7 for beauty competition not A6','Peer relationship not adversarial','Cross-chart arudha analysis unique to Jaimini'],
     'source':'Sanjay Rath - Crux of Vedic Astrology','partial':True},
    {'id':'SR-CS-018','name':'Franklin D Roosevelt','lagna':None,
     'planets':{'Jupiter':{'rashi':'Aries','house':9,'role':'Atmakaraka,1st/10th lord D-10'},'Rahu':{'house':4,'dignity':'debilitated','note':'vargottama'},'Mars':{'note':'debilitated in D-10'}},
     'dasha':{'md':'Rahu'},'outcome_domain':'political','outcome_positive':True,
     'outcome_description':'Political career from Rahu dasa 1910; debilitated malefic in kendra=Rajyoga at personal cost (polio)',
     'key_pattern':'debilitated_malefic_kendra_rajyoga','key_lesson':'Debilitated malefics in kendra give Rajyoga at personal cost; Rahu dasa splits into two phases via Rahu-Ketu midpoint',
     'reasoning_chain':['AK Jupiter in Aries 9th=political destiny','Jupiter 1st+10th lord in D-10 sits in 10th','Mars dasa: debilitated D-10=had to serve','Rahu dasa 1910=political career surfaced','Rahu debilitated 4th kendra=Rajyoga','Rahu vargottama=inclined to do good politically','First half Rahu-to-Ketu beneficial; second half=hibernation'],
     'source':'Sanjay Rath - Vimsottari & Udu Dasas','partial':True},
    {'id':'SR-CS-019','name':'Naveen Patnaik','lagna':None,
     'planets':{'Sun':{'house':3},'Mercury':{'position':'6th from AL','note':'debilitated navamsa'},'Jupiter':{'position':'6th from AL','note':'debilitated navamsa'},'Mars':{'position':'6th from AL'}},
     'dasha':{'md':'Saturn','ad':'Mercury'},'outcome_domain':'political','outcome_positive':True,
     'outcome_description':'CM Orissa via Vipareeta Rajyoga; father death triggered rise; Hora+Ghatika+Varnada lagnas confirm',
     'key_pattern':'vipareeta_rajyoga_from_al','key_lesson':'Vipareeta Rajyoga often manifests through tragedy; most afflicted benefic in worst position from AL gives strongest results',
     'reasoning_chain':['Mercury+Jupiter+Mars in 6th from AL','Benefics afflicted by malefic in dusthana from AL=Vipareeta Rajyoga','Both Mercury+Jupiter in debilitated navamsa','Father death Saturn-Jupiter=compelled to lead','Saturn-Mercury=became CM (strongest VRY planet)','Hora Lagna Taurus with AL','Ghatika Lagna has Dharma-Karmadhipati yoga','Varnada Lagna 2nd house=very high status'],
     'source':'Sanjay Rath - Vimsottari & Udu Dasas','partial':True},
    {'id':'SR-CS-020','name':'Dhirubhai Ambani','lagna':'Sagittarius',
     'planets':{'Jupiter':{'house':10,'role':'lagna lord,Moon sign lord,Sun sign lord,AL lord'},'Mars':{'rashi':'Leo','house':9,'role':'Atmakaraka','degree':'24deg09'}},
     'dasha':{'md':'Jupiter'},'outcome_domain':'wealth','outcome_positive':True,
     'outcome_description':'Greatest business tycoon; Jupiter lords lagna+Moon sign+Sun sign+AL; Jupiter dasa 1982-1998=greatest Reliance expansion',
     'key_pattern':'single_planet_multiple_lordships','key_lesson':'When one planet lords multiple critical points, its dasa is overwhelmingly powerful; convergence principle',
     'reasoning_chain':['Jupiter lords lagna+Moon sign+Sun sign+AL=all one planet','Jupiter in 10th=powerful Rajyoga','Jupiter dasa 1982-1998=Reliance expansion','Mars AK at 24deg09 Leo in 9th=fortune through aggression','Hora Lagna 27 Scorpio, Ghatika 5 Scorpio both 12th=foreign trade wealth'],
     'source':'Sanjay Rath - Vimsottari & Udu Dasas','partial':False},
    {'id':'SR-CS-021','name':'Elizabeth Taylor','lagna':None,
     'planets':{'Sun':{'rashi':'Leo','conjunction':'UL'},'Mars':{'rashi':'Virgo','conjunction':'Ketu'},'Venus':{'rashi':'Pisces'},'Rahu':{'rashi':'Pisces'},'Saturn':{'rashi':'Capricorn'}},
     'dasha':None,'outcome_domain':'marriage','outcome_positive':None,
     'outcome_description':'Eight marriages mapped via successive 8th from Upapada; Saturn=older spouse, Venus-Rahu=unconventional',
     'key_pattern':'successive_8th_from_upapada','key_lesson':'For multiple marriages count 8th from Upapada for each successive marriage; planets describe spouse nature',
     'reasoning_chain':['UL in Leo with Sun, 2nd Virgo has Mars+Ketu=1st marriage ended','8th from UL=Pisces with Venus+Rahu aspected by Saturn=2nd marriage to older Michael Wilding','Each successive marriage=8th from previous UL derivative','Saturn=older spouse, Venus-Rahu=unconventional','Same karmic pattern repeats across marriages'],
     'source':'Sanjay Rath - Vimsottari & Udu Dasas','partial':True},
    {'id':'SR-CS-022','name':'Ashtottari Foreign Residence','lagna':'Virgo',
     'planets':{'Rahu':{'rashi':'Capricorn'},'Mercury':{'rashi':'Aries','role':'lagna lord'},'Ketu':{'house':11},'Sun':{'role':'12th lord'},'Saturn':{'conjunction':'Mercury,Sun'}},
     'dasha':None,'outcome_domain':'career','outcome_positive':True,
     'outcome_description':'Foreign residence predicted; Ashtottari applicable (Rahu kendra from lagnesh+Krishna Paksha daytime birth)',
     'key_pattern':'ashtottari_applicability','key_lesson':'Check Ashtottari conditions always; operates alongside Vimsottari like different clocks showing different times',
     'reasoning_chain':['Rahu in Capricorn kendra to Mercury lagna lord in Aries=condition 1','Krishna Paksha daytime birth=condition 2','Ketu governor in 11th nakshatra of 12th lord Sun','Sun+Mercury+Saturn: 12th lord with lagnesh in 8th=foreign residence','Multiple dasa systems active simultaneously'],
     'source':'Sanjay Rath - Vimsottari & Udu Dasas','partial':False},
    {'id':'SR-CS-023','name':'Standard Nativity Cross Verification','lagna':None,
     'planets':{'Saturn':{'rashi':'Capricorn','degree':'26deg50R','role':'Atmakaraka'},'Jupiter':{'rashi':'Pisces','degree':'26deg08','role':'Amatyakaraka'},'Rahu':{'rashi':'Gemini','degree':'25deg46','role':'Darakaraka'}},
     'dasha':None,'outcome_domain':'death','outcome_positive':None,
     'outcome_description':'Cross-verification via Utpanna, Kshema, Adhana dasa against Janma Vimsottari; convergence=certainty',
     'key_pattern':'triple_vimsottari_cross_check','key_lesson':'Never rely on single dasa; check Utpanna+Kshema+Adhana ending dates; convergence=certain event',
     'reasoning_chain':['Janma Nakshatra Satabhisaj','Kshema star Revati ruled Mercury','Utpanna star Aswini ruled Ketu','Adhana star Rohini ruled Moon','Compare ending dates across all three against Janma Vimsottari','Convergence indicates critical life events'],
     'source':'Sanjay Rath - Vimsottari & Udu Dasas','partial':True},
    {'id':'SR-CS-024','name':'Standard Nativity Dictums','lagna':None,
     'planets':{'Sun':{'position':'in A9'},'Saturn':{'aspect_on':'Sun in A9'},'Rahu':{'aspect_on':'Sun in A9'},'Jupiter':{'house':1},'Mars':{'position':'Marana Karaka Sthana'},'Mercury':{'role':'7th lord','position':'6th house'}},
     'dasha':None,'outcome_domain':'career','outcome_positive':None,
     'outcome_description':'Multiple dictums tested: Sun in A9 with Saturn/Rahu=father ruined; Jupiter lagna=protection; Mars MKS=business destroyed',
     'key_pattern':'dictum_activation_by_dasa','key_lesson':'Dictums activate in specific dasa periods; Jupiter in lagna is most protective but cannot override strong malefic dasas',
     'reasoning_chain':['Sun in A9 aspected Saturn+Rahu: Rahu-Sun dasa father gave up job=disastrous','Jupiter dasa=most beneficial, father set up huge business','Mars MKS: Mars dasa=entire business destroyed within year','Mercury 7th lord in 6th: married poor family in Mercury dasa','Jupiter lagna=dog bite cured (protective)','Each dictum activates in corresponding dasa'],
     'source':'Sanjay Rath - Vimsottari & Udu Dasas','partial':True},
    {'id':'SR-CS-025','name':'Sri Chaitanya Mahaprabhu','lagna':None,
     'planets':{},'dasha':None,'outcome_domain':'spiritual','outcome_positive':True,
     'outcome_description':'Dwisaptati Sama Dasa applied; born exact Sandhya Kala full Moon; Rudra connection; 9-year equal periods',
     'key_pattern':'dwisaptati_dasa_rudra','key_lesson':'Dwisaptati applies when Rudra/Shiva connection strong; not universally applicable; suited to devotion-oriented charts',
     'reasoning_chain':['Dwisaptati: equal 9-year periods for 8 planets','Count Moola to Janma nakshatra, expunge 8','Birth at exact Sandhya Kala full Moon','Shiva-Hari Hara Brahma yoga','Strong Rudra connection=dasa applicable','Equal periods mirror Shoola dasa'],
     'source':'Sanjay Rath - Vimsottari & Udu Dasas','partial':True},
    {'id':'SR-CS-026','name':'Dwadasottari Venus Theme','lagna':'Pisces',
     'planets':{'Venus':{'rashi':'Pisces','degree':'28deg08','note':'same sign in Rasi and Navamsa'},'Moon':{'degree':'29deg41','role':'Atmakaraka'}},
     'dasha':None,'outcome_domain':'career','outcome_positive':True,
     'outcome_description':'Life full of Venusian themes; Dwadasottari applies when lagna=Venus navamsa sign; Venus becomes life theme governor',
     'key_pattern':'dwadasottari_venus_theme','key_lesson':'When Dwadasottari applies, Venus becomes thematic anchor; condition: lagna=Venus navamsa sign',
     'reasoning_chain':['Venus in Pisces Rasi AND Pisces Navamsa','Lagna also Pisces=matches Venus navamsa sign','Condition satisfied: Dwadasottari applies','Entire life read through Venus lens','Moon AK at 29deg41, Venus AmK at 28deg08'],
     'source':'Sanjay Rath - Vimsottari & Udu Dasas','partial':False},
    {'id':'SR-CS-027','name':'Vivekananda Full Life Vimsottari','lagna':'Sagittarius',
     'planets':{'Jupiter':{'role':'Ista Devata,lagna lord'},'Mars':{'role':'12th lord'},'Sun':{'role':'9th lord,Yogada','conjunction':'Hora Lagna,Ghatika Lagna'},'Moon':{'role':'8th lord','conjunction':'Saturn 2nd lord'}},
     'dasha':{'md':'Sun','ad':'Moon'},'outcome_domain':'spiritual','outcome_positive':True,
     'outcome_description':'Complete life: Jupiter dasa=spiritual mission/USA; Sun dasa=Ramakrishna Mission founded; Sun-Moon=death July 4 1902',
     'key_pattern':'yogada_sun_triple_lagna','key_lesson':'Yogada planet (conjoining HL+GL+Lagna) is most powerful in any chart; badhakesh kendra planets enable foreign travel',
     'reasoning_chain':['Jupiter Ista Devata=spiritual empowerment','Jupiter+Mars Rajyoga: 4th/5th lords, both movable=foreign travel','Sun 9th lord Yogada conjoining HL+GL=most powerful','Sun dasa=Parliament of Religions+Ramakrishna Mission','Planets in kendra to badhakesh=foreign travel','Death Sun-Moon: Moon 8th lord from lagna and AK','Sun debilitated in Trimsamsa D-30'],
     'source':'Sanjay Rath - Vimsottari & Udu Dasas','partial':False},
    {'id':'SR-CS-028','name':'BJP Leader Saturn Dasa Rajyoga','lagna':None,
     'planets':{'Saturn':{'position':'in Mantra Pada'},'Venus':{'position':'8th from Saturn in D-10'},'Ketu':{'position':'3rd from Saturn'},'Jupiter':{'dignity':'debilitated','conjunction':'Ketu'}},
     'dasha':{'md':'Saturn','ad':'Ketu','pd':'Venus'},'outcome_domain':'political','outcome_positive':True,
     'outcome_description':'Babri Masjid Dec 6 1992 in Saturn-Saturn-Venus; became Defense Minister in Saturn-Ketu-Venus; Venus consistent activator',
     'key_pattern':'saturn_dasa_3rd_8th_benefic','key_lesson':'Within Saturn dasa: benefics 3rd/8th from Saturn deliver Rajyoga; pratyantardasa can be more important than antardasa',
     'reasoning_chain':['Until Rahu dasa end=career insignificant','Jupiter dasa=rose through alliance','Saturn in Mantra Pada=power promised','Venus 8th from Saturn D-10=promises power','Saturn-Saturn-Venus: Babri Masjid fell','Saturn-Ketu-Venus: became Defense Minister','Venus consistently activates as pratyantardasa','Ketu 3rd from Saturn+debilitated Jupiter=instability threat'],
     'source':'Sanjay Rath - Vimsottari & Udu Dasas','partial':True},
    {'id':'SR-CS-029','name':'Vimsottari Applicability Principle','lagna':None,
     'planets':{},'dasha':None,'outcome_domain':'career','outcome_positive':None,
     'outcome_description':'Vimsottari is default for commoners; Ashtottari for ~25% charts; multiple dasas work simultaneously like different clocks',
     'key_pattern':'multiple_dasa_coexistence','key_lesson':'Never assume Vimsottari is only applicable; check Ashtottari+Shodasottari+Dwadasottari+Dwisaptati conditions',
     'reasoning_chain':['Ashtottari oldest, predates Vimsottari','Vimsottari uses 27 nakshatra=mundane','Parasara advocated Vimsottari for commoners','Ashtottari in ~25% charts','Multiple dasas like different clocks','Shodasottari: Krishna Paksha Moon hora OR Sukla Paksha Sun hora'],
     'source':'Sanjay Rath - Vimsottari & Udu Dasas','partial':True},
    {'id':'SR-CS-030','name':'Dictum Planets from Arudha Lagna','lagna':None,
     'planets':{},'dasha':None,'outcome_domain':'career','outcome_positive':None,
     'outcome_description':'Systematic rules: benefics in 6/8/12 from AL=losses; malefics in same=Rajyoga; karaka supremacy over house lords',
     'key_pattern':'al_dusthana_reversal','key_lesson':'From AL: malefics in 6/8/12=Rajyoga, benefics=loss (opposite of lagna reading); karakas supreme over house lords',
     'reasoning_chain':['Rule 48: benefic in dusthana from AL=losses in its dasa','Rule 49: malefic in dusthana from AL=authority and power','Rule 50: karaka gives or takes away, lords only work for karaka','Rule 51: shastastaka forebodes evil except Mercury-Saturn in dusthana=Rajyoga','Vipareeta principle applied to Arudha'],
     'source':'Sanjay Rath - Vimsottari & Udu Dasas','partial':True},
    {'id':'SR-CS-031','name':'Navtara Chakra Framework','lagna':None,
     'planets':{},'dasha':None,'outcome_domain':'career','outcome_positive':None,
     'outcome_description':'Planets communicate through nakshatra relay not direct; three groups: Janma(self), Karma(career), Adhana(origin)',
     'key_pattern':'navtara_chakra_relay','key_lesson':'Dasa results pass through nakshatra relay system; group determines arena of effects',
     'reasoning_chain':['3 groups of 9 constellations from lagna and janma nakshatra','Janmarksha=body/self','Karmarksha=work/career','Adhanarksha=conception/origin','No hotline between planet and person','Nakshatra relay=intermediary'],
     'source':'Sanjay Rath - Vimsottari & Udu Dasas','partial':True},
    {'id':'SR-CS-032','name':'Sama Saptaka vs Unmada Yoga','lagna':None,
     'planets':{},'dasha':None,'outcome_domain':'health','outcome_positive':None,
     'outcome_description':'Saturn-Mars in 1-7=Unmada Yoga (madness); Jupiter-Mars in 1-7=Guru-Mangala Yoga (Sri Ram undefeatable)',
     'key_pattern':'1_7_axis_friendship_test','key_lesson':'Geometry alone does not determine yoga; natural+temporal friendship is decisive factor; same placement=greatest strength or greatest weakness',
     'reasoning_chain':['Sama-Saptaka requires SAMA or better relationship','Saturn-Mars: natural+temporal enemies in 1/7=Unmada Yoga=madness','Both in Marana Karaka Sthana','Jupiter-Mars 1/7=Guru-Mangala Yoga','Sri Ram undefeatable in battle','Same geometry, opposite results based on friendship'],
     'source':'Sanjay Rath - Vimsottari & Udu Dasas','partial':True},
]

# ==========================================================================
# STATS: Summary counts for backtesting dashboard
# ==========================================================================
STATS = {
    'total': len(GROUND_TRUTH),
    'with_lagna': sum(1 for c in GROUND_TRUTH if c['lagna'] is not None),
    'with_planets': sum(1 for c in GROUND_TRUTH if c['planets']),
    'with_dasha': sum(1 for c in GROUND_TRUTH if c['dasha'] is not None),
    'partial': sum(1 for c in GROUND_TRUTH if c['partial']),
    'complete': sum(1 for c in GROUND_TRUTH if not c['partial']),
    'by_domain': {},
    'by_source': {},
    'by_outcome': {'positive': 0, 'negative': 0, 'neutral': 0},
}

for _c in GROUND_TRUTH:
    _d = _c['outcome_domain']
    STATS['by_domain'][_d] = STATS['by_domain'].get(_d, 0) + 1
    _s = _c['source'].split(' - ')[0].strip()
    STATS['by_source'][_s] = STATS['by_source'].get(_s, 0) + 1
    if _c['outcome_positive'] is True:
        STATS['by_outcome']['positive'] += 1
    elif _c['outcome_positive'] is False:
        STATS['by_outcome']['negative'] += 1
    else:
        STATS['by_outcome']['neutral'] += 1
