#!/usr/bin/env bash
set -euo pipefail

# Generates a comprehensive contingency/disaster recovery document
# with live system state. Called by backup.sh before uploading to Google Drive.

NANOCLAW_DIR="${NANOCLAW_DIR:-/Users/amrut/nanoclaw}"
OUTPUT="${1:-${NANOCLAW_DIR}/data/contingency.md}"

DB="${NANOCLAW_DIR}/store/messages.db"
NOW=$(date '+%Y-%m-%d %H:%M %Z')

# Helper: get DB value safely
dbval() { sqlite3 "$DB" "$1" 2>/dev/null || echo "N/A"; }

# Pull live R2 credentials from rclone config so the contingency doc is self-contained.
# This file lives in private Google Drive — safe to inline secrets.
RCLONE_CONF="${HOME}/.config/rclone/rclone.conf"
get_rclone_val() {
    awk -v section="$1" -v key="$2" '
        /^\[/ { in_sec = ($0 == "[" section "]") }
        in_sec && $0 ~ "^" key " *=" { sub(/^[^=]*= */, ""); print; exit }
    ' "$RCLONE_CONF" 2>/dev/null
}
R2_ACCESS_KEY=$(get_rclone_val r2 access_key_id)
R2_SECRET_KEY=$(get_rclone_val r2 secret_access_key)
R2_ENDPOINT=$(get_rclone_val r2 endpoint)
[ -z "$R2_ACCESS_KEY" ] && R2_ACCESS_KEY="MISSING-from-rclone-conf"
[ -z "$R2_SECRET_KEY" ] && R2_SECRET_KEY="MISSING-from-rclone-conf"
[ -z "$R2_ENDPOINT" ] && R2_ENDPOINT="https://b6a5767fe078a25e1a0f15cdf6c91fd4.r2.cloudflarestorage.com"

# Gather live stats
MSG_COUNT=$(dbval "SELECT count(*) FROM messages;")
CHAT_COUNT=$(dbval "SELECT count(*) FROM chats;")
ACTIVE_TASKS=$(dbval "SELECT count(*) FROM scheduled_tasks WHERE status='active';")
TASK_LIST=$(dbval "SELECT id || ' (' || schedule_type || ': ' || schedule_value || ')' FROM scheduled_tasks WHERE status='active';" | sed 's/^/- /')
DB_SIZE=$(du -sh "$DB" 2>/dev/null | cut -f1 || echo "N/A")
STORE_SIZE=$(du -sh "${NANOCLAW_DIR}/store" 2>/dev/null | cut -f1 || echo "N/A")
GROUPS_SIZE=$(du -sh "${NANOCLAW_DIR}/groups" 2>/dev/null | cut -f1 || echo "N/A")
R2_SIZE=$(timeout 30 rclone size r2:nanoclaw-backup --json --max-depth 0 2>/dev/null | grep -o '"bytes":[0-9]*' | cut -d: -f2 || echo "0")
R2_MB=$(( ${R2_SIZE:-0} / 1048576 ))

NODE_VER=$(node --version 2>/dev/null || echo "not installed")
RCLONE_VER=$(rclone version --check 2>/dev/null | head -1 || rclone --version 2>/dev/null | head -1 || echo "not installed")

# Services status
SERVICES=""
for svc in com.nanoclaw com.nanoclaw.backup com.nanoclaw.cloudflared com.nanoclaw.mlx-server; do
    if launchctl list 2>/dev/null | grep -q "$svc"; then
        SERVICES="${SERVICES}\n| ${svc} | Running |"
    else
        SERVICES="${SERVICES}\n| ${svc} | Stopped |"
    fi
done

# Git branch info
NC_BRANCH=$(git -C "$NANOCLAW_DIR" rev-parse --abbrev-ref HEAD 2>/dev/null || echo "N/A")
NC_COMMIT=$(git -C "$NANOCLAW_DIR" log -1 --format='%h %s' 2>/dev/null || echo "N/A")
# .env key names (no values)
ENV_KEYS=$(grep -oE '^[A-Z_][A-Z_0-9]+=' "${NANOCLAW_DIR}/.env" 2>/dev/null | sed 's/=//' | sort | sed 's/^/- /' || echo "- (none found)")

# WhatsApp auth status
WA1_STATUS="Missing"
WA2_STATUS="Missing"
[ -d "${NANOCLAW_DIR}/store/auth" ] && [ "$(ls -A "${NANOCLAW_DIR}/store/auth" 2>/dev/null)" ] && WA1_STATUS="Present ($(du -sh "${NANOCLAW_DIR}/store/auth" | cut -f1))"
[ -d "${NANOCLAW_DIR}/store/auth2" ] && [ "$(ls -A "${NANOCLAW_DIR}/store/auth2" 2>/dev/null)" ] && WA2_STATUS="Present ($(du -sh "${NANOCLAW_DIR}/store/auth2" | cut -f1))"

mkdir -p "$(dirname "$OUTPUT")"

cat > "$OUTPUT" << DOCEOF
# NanoClaw — Contingency & Disaster Recovery

**Last updated:** ${NOW}
**Auto-generated by:** scripts/generate-contingency.sh (runs every 15 min)

---

## Quick Recovery (Complete System Loss)

If you lose your Mac (or want to spin up on a VPS / second machine), run **one command** on the new box:

\`\`\`bash
R2_ACCESS_KEY='${R2_ACCESS_KEY}' \\
R2_SECRET_KEY='${R2_SECRET_KEY}' \\
R2_ENDPOINT='${R2_ENDPOINT}' \\
bash <(curl -fsSL https://raw.githubusercontent.com/amruth9459/nanoclaw/main/scripts/bootstrap.sh)
\`\`\`

That's it. The bootstrap script handles:
1. Installing Homebrew (macOS) or apt deps (Linux) — rclone, git, node@20, python3, cloudflared
2. Configuring rclone with the R2 creds above
3. Restoring \`~/.ssh\` (keys, config, known_hosts) from R2
4. Cloning + restoring NanoClaw (\`~/nanoclaw\`) — runtime data, groups/, store/, .env
5. Cloning + restoring Lexios (\`~/Lexios\`) — corpus, work/, .env, Python venv
6. Restoring \`~/Brain\` (Obsidian vault), \`~/Downloads/Final report\` (HPM 523), \`~/Library/LaunchAgents\` (services)
7. Building NanoClaw (\`npm install && npm run build\`) + the agent container
8. Loading all launchd services (macOS only)

**Supported targets:** macOS (full), Linux/VPS via apt-get (everything except launchd + Docker container).

If you're already on the box and just want to refresh state without bootstrapping:
\`\`\`bash
cd ~/nanoclaw && ./scripts/restore.sh
cd ~/Lexios && ./scripts/restore.sh
\`\`\`

---

## Current System State

| Metric | Value |
|--------|-------|
| Messages stored | ${MSG_COUNT} |
| Chats tracked | ${CHAT_COUNT} |
| Active scheduled tasks | ${ACTIVE_TASKS} |
| Database size | ${DB_SIZE} |
| Store directory | ${STORE_SIZE} |
| Groups directory | ${GROUPS_SIZE} |
| R2 backup size | ${R2_MB}MB |
| Node.js version | ${NODE_VER} |

### Active Scheduled Tasks

${TASK_LIST:-None}

### Git State

| Repo | Branch | Latest Commit |
|------|--------|---------------|
| NanoClaw | ${NC_BRANCH} | ${NC_COMMIT} |

### Services

| Service | Status |
|---------|--------|$(echo -e "$SERVICES")

### WhatsApp Auth

| Account | Status |
|---------|--------|
| WA1 (primary) | ${WA1_STATUS} |
| WA2 (secondary) | ${WA2_STATUS} |

---

## Architecture Overview

\`\`\`
Mac Studio
├── Node.js process (src/index.ts → dist/index.js)
│   ├── WhatsApp channels via Baileys
│   ├── GroupQueue — message + task queueing per group
│   ├── Task Scheduler — cron/interval scheduled tasks
│   ├── IPC watcher — reads agent output from data/ipc/
│   ├── DashClaw — Express web dashboard on :8080
│   └── Resource Orchestrator — RAM/agent lifecycle
├── Docker containers (one per agent invocation)
│   ├── Claude Agent SDK (@anthropic-ai/sdk)
│   ├── MCP tools via IPC (send_message, react, schedule_task, etc.)
│   ├── Chromium + agent-browser for web automation
│   └── Skills (integration-provided + core)
├── SQLite databases (store/*.db)
├── Cloudflare Quick Tunnel (cloudflared → :8080)
└── MLX server (local LLM for routing classification)
\`\`\`

---

## Git Repositories

| Repo | Local Path | Remote | URL |
|------|-----------|--------|-----|
| NanoClaw | ~/nanoclaw | fork | https://github.com/amruth9459/nanoclaw.git |
| NanoClaw (upstream) | ~/nanoclaw | origin | https://github.com/qwibitai/nanoclaw.git |

---

## Backup System

### What's Backed Up (every 15 min to Cloudflare R2)

| Source | R2 Path | Notes |
|--------|---------|-------|
| store/*.db | nanoclaw/store/ | SQLite DBs (messages, economics) |
| store/auth*/ | nanoclaw/store/ | WhatsApp session keys |
| groups/ | nanoclaw/groups/ | Group data, conversations, CLAUDE.md |
| data/ | nanoclaw/data/ | Session state (excl transient IPC) |
| config/ | nanoclaw/config/ | Router config |
| .env | nanoclaw/env/dot-env | All secrets and config |

### What's NOT Backed Up (rebuild from source)

- node_modules/ — \`npm install\`
- dist/ — \`npm run build\`
- Docker image — \`./container/build.sh\`
- logs/ — transient, not needed for recovery
- LaunchD plists — see below for copies

### R2 Credentials

- **Bucket:** nanoclaw-backup
- **Account ID:** b6a5767fe078a25e1a0f15cdf6c91fd4
- **Endpoint:** https://b6a5767fe078a25e1a0f15cdf6c91fd4.r2.cloudflarestorage.com
- **API token location:** Cloudflare Dashboard → R2 → Manage R2 API Tokens

---

## Environment Variables (.env)

These keys must be present in .env for the system to function. Values are backed up to R2.

${ENV_KEYS}

**Critical secrets:**
- \`CLAUDE_CODE_OAUTH_TOKEN\` — Claude API auth (from Claude Max subscription)
- \`CLAW_EMAIL_APP_PASSWORD\` — Gmail app password for email integration

---

## LaunchD Services

### com.nanoclaw.plist (Main Service)

\`\`\`xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key><string>com.nanoclaw</string>
  <key>KeepAlive</key><true/>
  <key>RunAtLoad</key><true/>
  <key>ProgramArguments</key>
  <array>
    <string>/usr/bin/caffeinate</string>
    <string>-i</string><string>-s</string>
    <string>NODE_PATH/bin/node</string>
    <string>/Users/amrut/nanoclaw/dist/index.js</string>
  </array>
  <key>WorkingDirectory</key><string>/Users/amrut/nanoclaw</string>
  <key>EnvironmentVariables</key>
  <dict>
    <key>PATH</key><string>/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin</string>
    <key>NANOCLAW_ENABLE_PROMPT_CACHING</key><string>1</string>
    <key>NANOCLAW_ENABLE_STREAMING</key><string>1</string>
    <key>NANOCLAW_INSTANT_ACK</key><string>1</string>
    <key>NANOCLAW_OPEN_MENTIONS</key><string>1</string>
    <key>NANOCLAW_WA2</key><string>1</string>
    <!-- Integration-specific env vars added here -->
    <key>NANOCLAW_POLL_INTERVAL</key><string>500</string>
  </dict>
  <key>StandardErrorPath</key><string>/Users/amrut/nanoclaw/logs/nanoclaw.error.log</string>
</dict>
</plist>
\`\`\`

**Note:** Replace NODE_PATH with your nvm node path (currently \`/Users/amrut/.nvm/versions/node/v20.18.3\`).

### com.nanoclaw.backup.plist

\`\`\`xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key><string>com.nanoclaw.backup</string>
  <key>ProgramArguments</key>
  <array>
    <string>/bin/bash</string>
    <string>/Users/amrut/nanoclaw/scripts/backup.sh</string>
  </array>
  <key>EnvironmentVariables</key>
  <dict>
    <key>PATH</key><string>/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin</string>
  </dict>
  <key>WorkingDirectory</key><string>/Users/amrut/nanoclaw</string>
  <key>StartInterval</key><integer>900</integer>
  <key>RunAtLoad</key><true/>
  <key>Nice</key><integer>10</integer>
  <key>StandardOutPath</key><string>/Users/amrut/nanoclaw/logs/backup.log</string>
  <key>StandardErrorPath</key><string>/Users/amrut/nanoclaw/logs/backup-err.log</string>
</dict>
</plist>
\`\`\`

### com.nanoclaw.cloudflared.plist

\`\`\`xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key><string>com.nanoclaw.cloudflared</string>
  <key>ProgramArguments</key>
  <array>
    <string>/opt/homebrew/bin/cloudflared</string>
    <string>tunnel</string><string>--url</string><string>http://localhost:8080</string>
    <string>--logfile</string><string>/Users/amrut/nanoclaw/logs/cloudflared.log</string>
  </array>
  <key>RunAtLoad</key><true/>
  <key>KeepAlive</key><true/>
  <key>StandardErrorPath</key><string>/Users/amrut/nanoclaw/logs/cloudflared.error.log</string>
  <key>ThrottleInterval</key><integer>10</integer>
</dict>
</plist>
\`\`\`

---

## Database Schema (Key Tables)

\`\`\`sql
-- Messages
CREATE TABLE messages (
  id TEXT, chat_jid TEXT, sender TEXT, sender_name TEXT,
  content TEXT, timestamp TEXT, is_from_me INTEGER,
  is_bot_message INTEGER DEFAULT 0,
  media_type TEXT, media_path TEXT, media_mimetype TEXT, media_size INTEGER,
  PRIMARY KEY (id, chat_jid)
);

-- Scheduled Tasks
CREATE TABLE scheduled_tasks (
  id TEXT PRIMARY KEY, group_folder TEXT, chat_jid TEXT,
  prompt TEXT, schedule_type TEXT, schedule_value TEXT,
  context_mode TEXT DEFAULT 'group', status TEXT DEFAULT 'active',
  next_run TEXT, last_result TEXT, created_at TEXT
);

-- Economics
CREATE TABLE group_economics (
  group_folder TEXT PRIMARY KEY, total_input_tokens INTEGER DEFAULT 0,
  total_output_tokens INTEGER DEFAULT 0, total_cache_read INTEGER DEFAULT 0,
  total_cache_write INTEGER DEFAULT 0, total_cost_usd REAL DEFAULT 0,
  total_earned_usd REAL DEFAULT 0, updated_at TEXT
);
\`\`\`

---

## Specific Recovery Scenarios

### Scenario 1: WhatsApp Disconnected

Symptoms: No messages flowing, "connection lost" in logs.

\`\`\`bash
# Check service
launchctl list | grep nanoclaw

# Check logs
tail -50 ~/nanoclaw/logs/nanoclaw.error.log | grep -i "connect\|auth\|close"

# Restart service
launchctl unload ~/Library/LaunchAgents/com.nanoclaw.plist
launchctl load ~/Library/LaunchAgents/com.nanoclaw.plist

# If auth expired: re-scan QR code
# Open http://localhost:8080 or the cloudflared URL
# Follow QR scanning instructions
\`\`\`

### Scenario 2: Database Corruption

\`\`\`bash
# Stop service first
launchctl unload ~/Library/LaunchAgents/com.nanoclaw.plist

# Restore from R2
rclone copy r2:nanoclaw-backup/nanoclaw/store/messages.db ~/nanoclaw/store/

# Restart
launchctl load ~/Library/LaunchAgents/com.nanoclaw.plist
\`\`\`

### Scenario 3: Container Build Broken

\`\`\`bash
# Full clean rebuild
docker builder prune -af
./container/build.sh

# If Docker itself is broken, rebuild from scratch
# Install Docker Desktop or switch to Apple Container
\`\`\`

### Scenario 4: Lost .env File

\`\`\`bash
# Restore from R2
rclone copy r2:nanoclaw-backup/nanoclaw/env/ /tmp/env-restore/
mv /tmp/env-restore/dot-env ~/nanoclaw/.env
\`\`\`

### Scenario 5: Full Mac Replacement

Follow the "Quick Recovery" section at the top of this document.
Total recovery time: ~15 minutes (mostly npm install + container build).

---

## Emergency Contacts / Accounts

| Service | Dashboard |
|---------|-----------|
| Cloudflare R2 | https://dash.cloudflare.com → R2 Object Storage |
| GitHub (NanoClaw) | https://github.com/amruth9459/nanoclaw |
| Claude API | https://console.anthropic.com |
| DashClaw (local) | http://localhost:8080 |

---

*This document is auto-generated every 15 minutes by \`scripts/generate-contingency.sh\` and uploaded to Google Drive and Cloudflare R2.*
DOCEOF

echo "Contingency doc generated: $OUTPUT"
